In [66]:
# ver 2
import os
import json
import requests
import pandas as pd
from datetime import date,datetime
from io import StringIO
import boto3


current_script_path = os.path.abspath('')
parent_directory = os.path.dirname(current_script_path)
resolved_parent_directory = os.path.abspath(parent_directory)


# Initialize S3 Bucket
my_bucket = 'formula1-project-bucket' # already created on S3
s3_client = boto3.client('s3')
csv_buffer = StringIO()


class DataRetriever:
    def __init__(self,start_year,end_year,start_date,end_date):
        self.start_year = start_year
        self.end_year = end_year
        self.start_date = start_date
        self.end_date = end_date
        self.today = date.today()
        self.current_year = date.today().year
    
    def _fetch_data(self,url):
        try:
            response = requests.get(url)
            response.raise_for_status()
            json_data = response.json()
            return json_data
        except requests.exceptions.HTTPError as e:
            return f"Error: {e}"
        except requests.exceptions.RequestException as f:
            return f"Error: {f}"

    def _upload_to_s3(self,dataframe,filename):
        try:
            with StringIO() as csv_buffer:
                dataframe.to_csv(csv_buffer,index=False)
                response = s3_client.put_object(Body=csv_buffer.getvalue(),Bucket=my_bucket,Key=f'{filename}')
                status = response.get("ResponseMetadata",{}).get("HTTPStatusCode")
                if status == 200:
                    status_text = f"Successful S3 put_object {dataframe} response. Status - {status}."
                else:
                    status_text = f"Unsuccessful S3 put_object {dataframe} response. Status - {status}."      
            return status_text
        except Exception as e:
            return f"Error: {e}"
    
class Ergast(DataRetriever):

    def __init__(self,start_year,end_year,start_date,end_date):
        super().__init__(start_year,end_year,start_date,end_date)
        self.base_url = "http://ergast.com/api/f1"
        self.max_round_todate = None

    def get_season_list(self):
        season_list = []
        for year in range(self.start_year, self.end_year + 1):
            url = f"{self.base_url}/{year}.json"
            fetched = self._fetch_data(url)
            df = pd.DataFrame(fetched['MRData']['RaceTable']['Races'])
            season_list.append(df)
            
        if season_list:
            season_list_df = pd.concat(season_list, ignore_index=True)
            season_list_df['date'] = pd.to_datetime(season_list_df['date']).dt.date
            season_list_df['season'] = season_list_df['season'].astype('int')
            season_list_df['round'] = season_list_df['round'].astype('int')
            
            if self.max_round_todate is None:
                filtered_date = season_list_df[(season_list_df['season'] == self.current_year) & (season_list_df['date'] < self.today)]
                
                if not filtered_date.empty:
                    max_round = filtered_date.loc[filtered_date['date'].idxmax(), 'round']
                    self.max_round_todate = max_round.astype('int')
                else:
                    print("Filtered data is empty. No max round found.")
    
            
            # upload to S3 bucket
            result = self._upload_to_s3(season_list_df,'season_list.csv')
    
            return result
        else:
            return "No season_list data fetched for any year."
        
    def get_race_result(self):
        race_result = []
        for year in range(self.start_year,self.current_year+1):
            if year < self.current_year:
                for race_no in range(1,25):
                    url = f"{self.base_url}/{year}/{race_no}/results.json"
                    fetched = self._fetch_data(url)
                    if 'MRData' in fetched and 'RaceTable' in fetched['MRData'] and 'Races' in fetched['MRData']['RaceTable']:
                        race_data = fetched['MRData']['RaceTable']['Races']
                        if race_data:
                            df = pd.DataFrame(race_data[0]['Results'])
                            df['season'] = year
                            df['round'] = race_no
                            race_result.append(df)

            else:     
                for race_no in range(1,self.max_round_todate+1):
                    url = f"{self.base_url}/{year}/{race_no}/results.json"
                    fetched = self._fetch_data(url)
                    if 'MRData' in fetched and 'RaceTable' in fetched['MRData'] and 'Races' in fetched['MRData']['RaceTable']:
                        race_data = fetched['MRData']['RaceTable']['Races']
                        if race_data:
                            df = pd.DataFrame(race_data[0]['Results'])
                            df['season'] = year
                            df['round'] = race_no
                            race_result.append(df)
                            
        if race_result:
            race_result_df = pd.concat(race_result,ignore_index=True)
    
            # upload to S3 bucket
            result = self._upload_to_s3(race_result_df,'race_result.csv')
            return result
        else:
            return "No race_result data fetched for any year."


class OpenF1(DataRetriever):

    def __init__(self,start_year,end_year,start_date,end_date):
        super().__init__(start_year,end_year,start_date,end_date)
        self.base_url = "https://api.openf1.org/v1"
        self.session_key = None
    
    def get_meeting_info(self):
        url = f"{self.base_url}/meetings?year>={self.start_year}&year<={self.end_year}"
        fetched = self._fetch_data(url)
        meeting_info = pd.DataFrame(fetched)
        if not meeting_info.empty:
            # upload to S3 bucket
            result = self._upload_to_s3(meeting_info,'meeting_info.csv')
            return result
        else:
            return "No meeting_info data fetched for any year."
    
    
    def get_session_info(self):
        url = f"{self.base_url}/sessions?session_name=Race&date_start>={self.start_date}&date_end<={self.end_date}"
        fetched = self._fetch_data(url)
        session_info = pd.DataFrame(fetched)
        if self.session_key is None and not session_info.empty:
            self.session_key = list(set(session_info['session_key']))
            
        if not session_info.empty:
            # upload to S3 bucket
            result = self._upload_to_s3(session_info,'session_info.csv')
            return result
        else:
            return "No session_info data fetched for any year."
    
    
    def get_weather_info(self):
        weather_info = pd.DataFrame()
        try:
            # pull data only from related session keys (race sessions)
            for session in self.session_key:
                url = f"{self.base_url}/weather?session_key={session}"
                fetched = self._fetch_data(url)
                weather_info = weather_info._append(fetched,ignore_index=True)
                
            if not weather_info.empty:
                # upload to S3 bucket
                result = self._upload_to_s3(weather_info,'weather_info.csv')
                return result
            else:
                return "No weather_info data fetched for any year."
        except TypeError as e:
            return f"Error: {e}, session info is empty, couldn't get weather info."
        except Exception as f:
            return f"Error: {f}"
    
    
    def get_laps_data(self):
        laps_data = pd.DataFrame()
        try:
            # pull data only from related session keys (race sessions)
            for session in self.session_key:
                url = f"{self.base_url}/laps?session_key={session}"
                fetched = self._fetch_data(url)
                laps_data = laps_data._append(fetched,ignore_index=True)

            if not laps_data.empty:
                # upload to S3 bucket
                result = self._upload_to_s3(laps_data,'laps_data.csv')
                return result
            else:
                return "No laps_data data fetched for any year."
        except TypeError as e:
            return f"Error: {e}, session info is empty, couldn't get laps data."
        except Exception as f:
            return f"Error: {f}"


if __name__ == "__main__":
    start_year = date.today().year - 3
    end_year = date.today().year
    start_date = datetime(start_year,1,1).strftime("%Y-%m-%d")
    end_date = date.today()
    
    ergast = Ergast(start_year,end_year,start_date,end_date)
    openf1 = OpenF1(start_year,end_year,start_date,end_date)
    ergast.get_season_list()
    ergast.get_race_result()
    openf1.get_meeting_info()
    openf1.get_session_info()
    openf1.get_weather_info()
    openf1.get_laps_data()

In [55]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
test = pd.DataFrame(data)

# Initialize S3 Bucket
my_bucket = 'formula1-project-bucket' # already created on S3
s3_client = boto3.client('s3')
csv_buffer = StringIO()

def _upload_to_s3(dataframe):
    with StringIO() as csv_buffer:
        dataframe.to_csv(csv_buffer,index=False)
        response = s3_client.put_object(Body=csv_buffer.getvalue(),Bucket=my_bucket,Key=f'{dataframe}.csv')
        status = response.get("ResponseMetadata",{}).get("HTTPStatusCode")
        if status == 200:
            status_text = f"Successful S3 put_object {dataframe} response. Status - {status}."
        else:
            status_text = f"Unsuccessful S3 put_object {dataframe} response. Status - {status}."      
    return status_text

In [44]:
_upload_to_s3(test)

'Successful S3 put_object    calories  duration\n0       420        50\n1       380        40\n2       390        45 response. Status - 200.'

In [62]:
start_year = date.today().year - 3
end_year = date.today().year
start_date = datetime(start_year,1,1).strftime("%Y-%m-%d")
end_date = date.today()

ergast = Ergast(start_year,end_year,start_date,end_date)
# openf1 = OpenF1(start_year,end_year,start_date,end_date)
# ergast.get_season_list()
# ergast.get_race_result()
# openf1.get_meeting_info()
# openf1.get_session_info()
# openf1.get_weather_info()
# openf1.get_laps_data()

In [63]:
ergast.get_season_list()

"Successful S3 put_object     season  round                                                url  \\\n0     2021      1  http://en.wikipedia.org/wiki/2021_Bahrain_Gran...   \n1     2021      2  http://en.wikipedia.org/wiki/2021_Emilia_Romag...   \n2     2021      3  http://en.wikipedia.org/wiki/2021_Portuguese_G...   \n3     2021      4  http://en.wikipedia.org/wiki/2021_Spanish_Gran...   \n4     2021      5  http://en.wikipedia.org/wiki/2021_Monaco_Grand...   \n..     ...    ...                                                ...   \n85    2024     20  https://en.wikipedia.org/wiki/2024_Mexico_City...   \n86    2024     21  https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...   \n87    2024     22  https://en.wikipedia.org/wiki/2024_Las_Vegas_G...   \n88    2024     23  https://en.wikipedia.org/wiki/2024_Qatar_Grand...   \n89    2024     24  https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...   \n\n                     raceName  \\\n0          Bahrain Grand Prix   \n1   Emilia Romagna Grand Prix   \n2       Portuguese Grand Prix   \n3          Spanish Grand Prix   \n4           Monaco Grand Prix   \n..                        ...   \n85     Mexico City Grand Prix   \n86       São Paulo Grand Prix   \n87       Las Vegas Grand Prix   \n88           Qatar Grand Prix   \n89       Abu Dhabi Grand Prix   \n\n                                              Circuit        date       time  \\\n0   {'circuitId': 'bahrain', 'url': 'http://en.wik...  2021-03-28  15:00:00Z   \n1   {'circuitId': 'imola', 'url': 'http://en.wikip...  2021-04-18  13:00:00Z   \n2   {'circuitId': 'portimao', 'url': 'http://en.wi...  2021-05-02  14:00:00Z   \n3   {'circuitId': 'catalunya', 'url': 'http://en.w...  2021-05-09  13:00:00Z   \n4   {'circuitId': 'monaco', 'url': 'http://en.wiki...  2021-05-23  13:00:00Z   \n..                                                ...         ...        ...   \n85  {'circuitId': 'rodriguez', 'url': 'http://en.w...  2024-10-27  20:00:00Z   \n86  {'circuitId': 'interlagos', 'url': 'http://en....  2024-11-03  17:00:00Z   \n87  {'circuitId': 'vegas', 'url': 'https://en.wiki...  2024-11-23  06:00:00Z   \n88  {'circuitId': 'losail', 'url': 'http://en.wiki...  2024-12-01  17:00:00Z   \n89  {'circuitId': 'yas_marina', 'url': 'http://en....  2024-12-08  13:00:00Z   \n\n                                  FirstPractice  \\\n0                        {'date': '2021-03-26'}   \n1                        {'date': '2021-04-16'}   \n2                        {'date': '2021-04-30'}   \n3                        {'date': '2021-05-07'}   \n4                        {'date': '2021-05-21'}   \n..                                          ...   \n85  {'date': '2024-10-25', 'time': '18:30:00Z'}   \n86  {'date': '2024-11-01', 'time': '14:30:00Z'}   \n87  {'date': '2024-11-21', 'time': '02:30:00Z'}   \n88  {'date': '2024-11-29', 'time': '13:30:00Z'}   \n89  {'date': '2024-12-06', 'time': '09:30:00Z'}   \n\n                                 SecondPractice  \\\n0                        {'date': '2021-03-26'}   \n1                        {'date': '2021-04-16'}   \n2                        {'date': '2021-04-30'}   \n3                        {'date': '2021-05-07'}   \n4                        {'date': '2021-05-21'}   \n..                                          ...   \n85  {'date': '2024-10-25', 'time': '22:00:00Z'}   \n86  {'date': '2024-11-01', 'time': '18:30:00Z'}   \n87  {'date': '2024-11-21', 'time': '06:00:00Z'}   \n88  {'date': '2024-11-29', 'time': '17:30:00Z'}   \n89  {'date': '2024-12-06', 'time': '13:00:00Z'}   \n\n                                  ThirdPractice  \\\n0                        {'date': '2021-03-27'}   \n1                        {'date': '2021-04-17'}   \n2                        {'date': '2021-05-01'}   \n3                        {'date': '2021-05-08'}   \n4                        {'date': '2021-05-22'}   \n..                                          ...   \n85  {'date': '2024-10-26', 'time': '17:30:00Z'}   \n86                                          NaN   \n87  {'date': '2024-11-22', 'time': '02:30:00Z'}   \n88                                          NaN   \n89  {'date': '2024-12-07', 'time': '10:30:00Z'}   \n\n                                     Qualifying  \\\n0                        {'date': '2021-03-27'}   \n1                        {'date': '2021-04-17'}   \n2                        {'date': '2021-05-01'}   \n3                        {'date': '2021-05-08'}   \n4                        {'date': '2021-05-22'}   \n..                                          ...   \n85  {'date': '2024-10-26', 'time': '21:00:00Z'}   \n86  {'date': '2024-11-02', 'time': '18:00:00Z'}   \n87  {'date': '2024-11-22', 'time': '06:00:00Z'}   \n88  {'date': '2024-11-30', 'time': '17:00:00Z'}   \n89  {'date': '2024-12-07', 'time': '14:00:00Z'}   \n\n                                         Sprint  \n0                                           NaN  \n1                                           NaN  \n2                                           NaN  \n3                                           NaN  \n4                                           NaN  \n..                                          ...  \n85                                          NaN  \n86  {'date': '2024-11-02', 'time': '14:00:00Z'}  \n87                                          NaN  \n88  {'date': '2024-11-30', 'time': '13:00:00Z'}  \n89                                          NaN  \n\n[90 rows x 12 columns] response. Status - 200."

In [64]:
ergast.get_race_result()

"Successful S3 put_object      number position positionText points  \\\n0        44        1            1     25   \n1        33        2            2     18   \n2        77        3            3     16   \n3         4        4            4     12   \n4        11        5            5     10   \n...     ...      ...          ...    ...   \n1355      3       16           16      0   \n1356     77       17           17      0   \n1357     24       18           18      0   \n1358     18       19            R      0   \n1359     10       20            R      0   \n\n                                                 Driver  \\\n0     {'driverId': 'hamilton', 'permanentNumber': '4...   \n1     {'driverId': 'max_verstappen', 'permanentNumbe...   \n2     {'driverId': 'bottas', 'permanentNumber': '77'...   \n3     {'driverId': 'norris', 'permanentNumber': '4',...   \n4     {'driverId': 'perez', 'permanentNumber': '11',...   \n...                                                 ...   \n1355  {'driverId': 'ricciardo', 'permanentNumber': '...   \n1356  {'driverId': 'bottas', 'permanentNumber': '77'...   \n1357  {'driverId': 'zhou', 'permanentNumber': '24', ...   \n1358  {'driverId': 'stroll', 'permanentNumber': '18'...   \n1359  {'driverId': 'gasly', 'permanentNumber': '10',...   \n\n                                            Constructor grid laps    status  \\\n0     {'constructorId': 'mercedes', 'url': 'http://e...    2   56  Finished   \n1     {'constructorId': 'red_bull', 'url': 'http://e...    1   56  Finished   \n2     {'constructorId': 'mercedes', 'url': 'http://e...    3   56  Finished   \n3     {'constructorId': 'mclaren', 'url': 'http://en...    7   56  Finished   \n4     {'constructorId': 'red_bull', 'url': 'http://e...    0   56  Finished   \n...                                                 ...  ...  ...       ...   \n1355  {'constructorId': 'rb', 'url': 'http://en.wiki...   14   49    +1 Lap   \n1356  {'constructorId': 'sauber', 'url': 'http://en....   16   49    +1 Lap   \n1357  {'constructorId': 'sauber', 'url': 'http://en....   20   49    +1 Lap   \n1358  {'constructorId': 'aston_martin', 'url': 'http...   10    5  Accident   \n1359  {'constructorId': 'alpine', 'url': 'http://en....   18    1   Gearbox   \n\n                                              Time  \\\n0     {'millis': '5523897', 'time': '1:32:03.897'}   \n1          {'millis': '5524642', 'time': '+0.745'}   \n2         {'millis': '5561280', 'time': '+37.383'}   \n3         {'millis': '5570363', 'time': '+46.466'}   \n4         {'millis': '5575944', 'time': '+52.047'}   \n...                                            ...   \n1355                                           NaN   \n1356                                           NaN   \n1357                                           NaN   \n1358                                           NaN   \n1359                                           NaN   \n\n                                             FastestLap  season  round  \n0     {'rank': '4', 'lap': '44', 'Time': {'time': '1...    2021      1  \n1     {'rank': '2', 'lap': '41', 'Time': {'time': '1...    2021      1  \n2     {'rank': '1', 'lap': '56', 'Time': {'time': '1...    2021      1  \n3     {'rank': '6', 'lap': '38', 'Time': {'time': '1...    2021      1  \n4     {'rank': '3', 'lap': '44', 'Time': {'time': '1...    2021      1  \n...                                                 ...     ...    ...  \n1355  {'rank': '16', 'lap': '47', 'Time': {'time': '...    2024      2  \n1356  {'rank': '14', 'lap': '49', 'Time': {'time': '...    2024      2  \n1357  {'rank': '6', 'lap': '49', 'Time': {'time': '1...    2024      2  \n1358  {'rank': '19', 'lap': '5', 'Time': {'time': '1...    2024      2  \n1359                                                NaN    2024      2  \n\n[1360 rows x 13 columns] response. Status - 200."

In [2]:
import os
# from urllib.request import urlopen
import json
import requests
import pandas as pd
import numpy as np
from datetime import date,datetime
import psycopg2
from io import StringIO
import boto3

In [9]:
current_script_path = os.path.abspath('')
parent_directory = os.path.dirname(current_script_path)
resolved_parent_directory = os.path.abspath(parent_directory)

In [6]:
# Initialize S3 Bucket
my_bucket = 'formula1-project-bucket' # already created on S3
csv_buffer = StringIO()
s3_resource = boto3.resource('s3')

In [7]:
# ver 1

class DataRetriever:
    def __init__(self,start_year,end_year,start_date,end_date):
        self.start_year = start_year
        self.end_year = end_year
        self.start_date = start_date
        self.end_date = end_dates
        self.today = date.today()
        self.current_year = date.today().year
    
    def _fetch_data(self,url):
        try:
            response = requests.get(url)
            response.raise_for_status()
            json_data = response.json()
            return json_data
        except requests.exceptions.HTTPError as e:
            return f"Error: {e}"
        except requests.exceptions.RequestException as f:
            return f"Error: {f}"

    
class Ergast(DataRetriever):

    def __init__(self,start_year,end_year,start_date,end_date):
        super().__init__(start_year,end_year,start_date,end_date)
        self.base_url = "http://ergast.com/api/f1"
        self.max_round_todate = None

    def get_season_list(self):
        season_list = []
        for year in range(self.start_year, self.end_year + 1):
            url = f"{self.base_url}/{year}.json"
            fetched = self._fetch_data(url)
            df = pd.DataFrame(fetched['MRData']['RaceTable']['Races'])
            season_list.append(df)
        
        combined_season_df = pd.concat(season_list, ignore_index=True)
        combined_season_df['date'] = pd.to_datetime(combined_season_df['date']).dt.date
        combined_season_df['season'] = combined_season_df['season'].astype('int')
        combined_season_df['round'] = combined_season_df['round'].astype('int')
        
        if self.max_round_todate is None:
            filtered_date = combined_season_df[(combined_season_df['season'] == self.current_year) & (combined_season_df['date'] < self.today)]
            
            if not filtered_date.empty:
                max_round = filtered_date.loc[filtered_date['date'].idxmax(), 'round']
                self.max_round_todate = max_round.astype('int')
            else:
                print("Filtered data is empty. No max round found.")
    
        # upload to S3 bucket
        combined_season_df.to_csv(csv_buffer,index=False)
        s3_resource.Object(my_bucket, 'season_list.csv').put(Body=csv_buffer.getvalue())
        return combined_season_df
        
    def get_race_result(self):
        race_result = []
        for year in range(self.start_year,self.current_year+1):
            if year < self.current_year:
                for race_no in range(1,25):
                    url = f"{self.base_url}/{year}/{race_no}/results.json"
                    fetched = self._fetch_data(url)
                    if 'MRData' in fetched and 'RaceTable' in fetched['MRData'] and 'Races' in fetched['MRData']['RaceTable']:
                        race_data = fetched['MRData']['RaceTable']['Races']
                        if race_data:
                            df = pd.DataFrame(race_data[0]['Results'])
                            df['season'] = year
                            df['round'] = race_no
                            race_result.append(df)

            else:     
                for race_no in range(1,self.max_round_todate+1):
                    url = f"{self.base_url}/{year}/{race_no}/results.json"
                    fetched = self._fetch_data(url)
                    if 'MRData' in fetched and 'RaceTable' in fetched['MRData'] and 'Races' in fetched['MRData']['RaceTable']:
                        race_data = fetched['MRData']['RaceTable']['Races']
                        if race_data:
                            df = pd.DataFrame(race_data[0]['Results'])
                            df['season'] = year
                            df['round'] = race_no
                            race_result.append(df)
        
        combined_race_result = pd.concat(race_result,ignore_index=True)
        # upload to S3 bucket
        combined_race_result.to_csv(csv_buffer,index=False)
        s3_resource.Object(my_bucket, 'race_result.csv').put(Body=csv_buffer.getvalue())
        return combined_race_result


class OpenF1(DataRetriever):

    def __init__(self,start_year,end_year,start_date,end_date):
        super().__init__(start_year,end_year,start_date,end_date)
        self.base_url = "https://api.openf1.org/v1"
        self.session_key = None
    
    def get_meeting_info(self):
        url = f"{self.base_url}/meetings?year>={self.start_year}&year<={self.end_year}"
        fetched = self._fetch_data(url)
        meeting_info = pd.DataFrame(fetched)
        # upload to S3 bucket
        meeting_info.to_csv(csv_buffer,index=False)
        s3_resource.Object(my_bucket, 'meeting_info.csv').put(Body=csv_buffer.getvalue())
        return meeting_info
    
    
    def get_session_info(self):
        url = f"{self.base_url}/sessions?session_name=Race&date_start>={self.start_date}&date_end<={self.end_date}"
        fetched = self._fetch_data(url)
        session_info = pd.DataFrame(fetched)
        if self.session_key is None and not session_info.empty:
            self.session_key = list(set(session_info['session_key']))
            
        # upload to S3 bucket
        session_info.to_csv(csv_buffer,index=False)
        s3_resource.Object(my_bucket, 'session_info.csv').put(Body=csv_buffer.getvalue())
        return session_info
    
    
    def get_weather_info(self):
        weather_info = pd.DataFrame()
        try:
            # pull data only from related session keys (race sessions)
            for session in self.session_key:
                url = f"{self.base_url}/weather?session_key={session}"
                fetched = self._fetch_data(url)
                weather_info = weather_info._append(fetched,ignore_index=True)
                
            # upload to S3 bucket
            weather_info.to_csv(csv_buffer,index=False)
            s3_resource.Object(my_bucket, 'weather_info.csv').put(Body=csv_buffer.getvalue())
            return weather_info
        except TypeError as e:
            return f"Error: {e}, session info is empty, couldn't get weather info."
        except Exception as f:
            return f"Error: {f}"
    
    
    def get_laps_data(self):
        laps_data = pd.DataFrame()
        try:
            # pull data only from related session keys (race sessions)
            for session in self.session_key:
                url = f"{self.base_url}/laps?session_key={session}"
                fetched = self._fetch_data(url)
                laps_data = laps_data._append(fetched,ignore_index=True)

            # upload to S3 bucket
            laps_data.to_csv(csv_buffer,index=False)
            s3_resource.Object(my_bucket, 'laps_data.csv').put(Body=csv_buffer.getvalue())
            return laps_data
        except TypeError as e:
            return f"Error: {e}, session info is empty, couldn't get laps data."
        except Exception as f:
            return f"Error: {f}"

# def get_car_data(self):
#     car_data = pd.DataFrame()
#     for session in self.session_key:
#         url = f"https://api.openf1.org/v1/car_data?session_key={session}"
#         fetched = self._fetch_data(url)
#         if not fetched.empty:
#             car_data = car_data._append(fetched,ignore_index=True)
#     return car_data

if __name__ == "__main__":
    start_year = date.today().year - 3
    end_year = date.today().year
    start_date = datetime(start_year,1,1).strftime("%Y-%m-%d")
    end_date = date.today()
    
    ergast = Ergast(start_year,end_year,start_date,end_date)
    openf1 = OpenF1(start_year,end_year,start_date,end_date)
    ergast.get_season_list()
    ergast.get_race_result()
    openf1.get_meeting_info()
    openf1.get_session_info()
    openf1.get_weather_info()
    openf1.get_laps_data()

In [13]:
url = f'http://ergast.com/api/f1/2021.json'
response = requests.get(url)
response.raise_for_status()
if response.status_code != 204:
    json_data = response.json()

In [17]:
df.loc[0,'Circuit']

{'circuitId': 'bahrain',
 'url': 'http://en.wikipedia.org/wiki/Bahrain_International_Circuit',
 'circuitName': 'Bahrain International Circuit',
 'Location': {'lat': '26.0325',
  'long': '50.5106',
  'locality': 'Sakhir',
  'country': 'Bahrain'}}

In [14]:
df = pd.DataFrame(json_data['MRData']['RaceTable']['Races'])
df

,season,round,url,raceName,Circuit,date,time,FirstPractice,SecondPractice,ThirdPractice,Qualifying,Sprint
0,2021,1,http://en.wikipedia.org/wiki/2021_Bahrain_Gran...,Bahrain Grand Prix,"{'circuitId': 'bahrain', 'url': 'http://en.wik...",2021-03-28,15:00:00Z,{'date': '2021-03-26'},{'date': '2021-03-26'},{'date': '2021-03-27'},{'date': '2021-03-27'},NaN
1,2021,2,http://en.wikipedia.org/wiki/2021_Emilia_Romag...,Emilia Romagna Grand Prix,"{'circuitId': 'imola', 'url': 'http://en.wikip...",2021-04-18,13:00:00Z,{'date': '2021-04-16'},{'date': '2021-04-16'},{'date': '2021-04-17'},{'date': '2021-04-17'},NaN
2,2021,3,http://en.wikipedia.org/wiki/2021_Portuguese_G...,Portuguese Grand Prix,"{'circuitId': 'portimao', 'url': 'http://en.wi...",2021-05-02,14:00:00Z,{'date': '2021-04-30'},{'date': '2021-04-30'},{'date': '2021-05-01'},{'date': '2021-05-01'},NaN
3,2021,4,http://en.wikipedia.org/wiki/2021_Spanish_Gran...,Spanish Grand Prix,"{'circuitId': 'catalunya', 'url': 'http://en.w...",2021-05-09,13:00:00Z,{'date': '2021-05-07'},{'date': '2021-05-07'},{'date': '2021-05-08'},{'date': '2021-05-08'},NaN
4,2021,5,http://en.wikipedia.org/wiki/2021_Monaco_Grand...,Monaco Grand Prix,"{'circuitId': 'monaco', 'url': 'http://en.wiki...",2021-05-23,13:00:00Z,{'date': '2021-05-21'},{'date': '2021-05-21'},{'date': '2021-05-22'},{'date': '2021-05-22'},NaN
5,2021,6,http://en.wikipedia.org/wiki/2021_Azerbaijan_G...,Azerbaijan Grand Prix,"{'circuitId': 'baku', 'url': 'http://en.wikipe...",2021-06-06,12:00:00Z,{'date': '2021-06-04'},{'date': '2021-06-04'},{'date': '2021-06-05'},{'date': '2021-06-05'},NaN
6,2021,7,http://en.wikipedia.org/wiki/2021_French_Grand...,French Grand Prix,"{'circuitId': 'ricard', 'url': 'http://en.wiki...",2021-06-20,13:00:00Z,{'date': '2021-06-18'},{'date': '2021-06-18'},{'date': '2021-06-19'},{'date': '2021-06-19'},NaN
7,2021,8,http://en.wikipedia.org/wiki/2021_Styrian_Gran...,Styrian Grand Prix,"{'circuitId': 'red_bull_ring', 'url': 'http://...",2021-06-27,13:00:00Z,{'date': '2021-06-25'},{'date': '2021-06-25'},{'date': '2021-06-26'},{'date': '2021-06-26'},NaN
8,2021,9,http://en.wikipedia.org/wiki/2021_Austrian_Gra...,Austrian Grand Prix,"{'circuitId': 'red_bull_ring', 'url': 'http://...",2021-07-04,13:00:00Z,{'date': '2021-07-02'},{'date': '2021-07-02'},{'date': '2021-07-03'},{'date': '2021-07-03'},NaN
9,2021,10,http://en.wikipedia.org/wiki/2021_British_Gran...,British Grand Prix,"{'circuitId': 'silverstone', 'url': 'http://en...",2021-07-18,14:00:00Z,{'date': '2021-07-16'},{'date': '2021-07-17'},NaN,{'date': '2021-07-16'},{'date': '2021-07-17'}
10,2021,11,http://en.wikipedia.org/wiki/2021_Hungarian_Gr...,Hungarian Grand Prix,"{'circuitId': 'hungaroring', 'url': 'http://en...",2021-08-01,13:00:00Z,{'date': '2021-07-30'},{'date': '2021-07-30'},{'date': '2021-07-31'},{'date': '2021-07-31'},NaN
11,2021,12,http://en.wikipedia.org/wiki/2021_Belgian_Gran...,Belgian Grand Prix,"{'circuitId': 'spa', 'url': 'http://en.wikiped...",2021-08-29,13:00:00Z,{'date': '2021-08-27'},{'date': '2021-08-27'},{'date': '2021-08-28'},{'date': '2021-08-28'},NaN
12,2021,13,http://en.wikipedia.org/wiki/2021_Dutch_Grand_...,Dutch Grand Prix,"{'circuitId': 'zandvoort', 'url': 'http://en.w...",2021-09-05,13:00:00Z,{'date': '2021-09-03'},{'date': '2021-09-03'},{'date': '2021-09-04'},{'date': '2021-09-04'},NaN
13,2021,14,http://en.wikipedia.org/wiki/2021_Italian_Gran...,Italian Grand Prix,"{'circuitId': 'monza', 'url': 'http://en.wikip...",2021-09-12,13:00:00Z,{'date': '2021-09-10'},{'date': '2021-09-11'},NaN,{'date': '2021-09-10'},{'date': '2021-09-11'}
14,2021,15,http://en.wikipedia.org/wiki/2021_Russian_Gran...,Russian Grand Prix,"{'circuitId': 'sochi', 'url': 'http://en.wikip...",2021-09-26,12:00:00Z,{'date': '2021-09-24'},{'date': '2021-09-24'},{'date': '2021-09-25'},{'date': '2021-09-25'},NaN
15,2021,16,http://en.wikipedia.org/wiki/2021_Turkish_Gran...,Turkish Grand Prix,"{'circuitId': 'istanbul', 'url': 'http://en.wi...",2021-10-10,12:00:00Z,{'date': '2021-10-08'},{'date': '2021-10-08'},{'date': '2021-10-09'},{'date': '2021-10-09'},NaN
16,2021,17,http://en.wikipedia.org/wiki/2021_United_State...,United States Grand Prix,"{'circuitId': 'americas', 'url': 'http://en.wi...",2021-10-24,19:00:00Z,{'date': '2021-10-22'},{'date': '2021-10-22'},{'date': '2021-10-23'},{'date': '2021-10-23'},NaN
17,2021,18,http://en.wikipedia.org/wiki/2021_Mexican_Gran...,Mexico City Grand Prix,"{'circuitId': 'rodriguez', 'url': 'http://en.w...",2021-11-07,19:00:00Z,{'date': '2021-11-05'},{'date': '2021-11-05'},{'date': '2021-11-06'},{'date': '2021-11-06'},NaN
18,2021,19,http://en.wikipedia.org/wiki/2021_S%C3%A3o_Pau...,São Paulo Grand Prix,"{'circuitId': 'interlagos', 'url': 'http://en....",2021-11-14,17:00:00Z,{'date': '2021-11-12'},{'date': '2021-11-13'},NaN,{'date': '2021-11-12'},{'date': '2021-11-13'}
19,2021,20,http://en.wikipedia.org/wiki/2021_Qatar_Grand_...,Qatar Grand Prix,"{'circuitId': 'losail', 'url': 'http://en.wiki...",2021-11-21,14:00:00Z,{'date': '2021-11-19'},{'date': '2021-11-19'},{'date': '2021-11-20'},{'date': '2021-11-20'},NaN
20,2021,21,http://en.wikipedia.org/wiki/2021_Saudi_Arabia...,Saudi Arabian Grand Prix,"{'circuitId': 'jeddah', 'url': 'http://en.wiki...",2021-12-05,17:30:00Z,{'date': '2021-12-03'},{'date': '2021-12-03'},{'date': '2021-12-04'},{'date': '2021-12-04'},NaN
21,2021,22,http://en.wikipedia.org/wiki/2021_Abu_Dhabi_Gr...,Abu Dhabi Grand Prix,"{'circuitId': 'yas_marina', 'url': 'http://en....",2021-12-12,13:00:00Z,{'date': '2021-12-10'},{'date': '2021-12-10'},{'date': '2021-12-11'},{'date': '2021-12-11'},NaN

In [ ]:
start_year = 2020
today = date.today()
current_year = today.year

In [39]:
date.today().year

2024

In [236]:
# Season list
def get_season_list(start_year,end_year):
    season_list = pd.DataFrame()
    for year in range(start_year,end_year+1):
        url = f"http://ergast.com/api/f1/{year}.json"
        try:
            response = requests.get(url)
            response.raise_for_status()
            if response.status_code != 204:
                json_data = response.json()     
        except:
            pass
        df = pd.DataFrame(json_data['MRData']['RaceTable']['Races']) 
        season_list = season_list._append(df)
    season_list.to_csv("season_list.csv")
    return season_list

In [237]:
get_season_list()

getting season list...

,season,round,url,raceName,Circuit,date,time,FirstPractice,SecondPractice,ThirdPractice,Qualifying,Sprint
0,2020,1,http://en.wikipedia.org/wiki/2020_Austrian_Gra...,Austrian Grand Prix,"{'circuitId': 'red_bull_ring', 'url': 'http://...",2020-07-05,13:10:00Z,NaN,NaN,NaN,NaN,NaN
1,2020,2,http://en.wikipedia.org/wiki/2020_Styrian_Gran...,Styrian Grand Prix,"{'circuitId': 'red_bull_ring', 'url': 'http://...",2020-07-12,13:10:00Z,NaN,NaN,NaN,NaN,NaN
2,2020,3,http://en.wikipedia.org/wiki/2020_Hungarian_Gr...,Hungarian Grand Prix,"{'circuitId': 'hungaroring', 'url': 'http://en...",2020-07-19,13:10:00Z,NaN,NaN,NaN,NaN,NaN
3,2020,4,http://en.wikipedia.org/wiki/2020_British_Gran...,British Grand Prix,"{'circuitId': 'silverstone', 'url': 'http://en...",2020-08-02,13:10:00Z,NaN,NaN,NaN,NaN,NaN
4,2020,5,http://en.wikipedia.org/wiki/70th_Anniversary_...,70th Anniversary Grand Prix,"{'circuitId': 'silverstone', 'url': 'http://en...",2020-08-09,13:10:00Z,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
19,2024,20,https://en.wikipedia.org/wiki/2024_Mexico_City...,Mexico City Grand Prix,"{'circuitId': 'rodriguez', 'url': 'http://en.w...",2024-10-27,20:00:00Z,"{'date': '2024-10-25', 'time': '18:30:00Z'}","{'date': '2024-10-25', 'time': '22:00:00Z'}","{'date': '2024-10-26', 'time': '17:30:00Z'}","{'date': '2024-10-26', 'time': '21:00:00Z'}",NaN
20,2024,21,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,São Paulo Grand Prix,"{'circuitId': 'interlagos', 'url': 'http://en....",2024-11-03,17:00:00Z,"{'date': '2024-11-01', 'time': '14:30:00Z'}","{'date': '2024-11-01', 'time': '18:30:00Z'}",NaN,"{'date': '2024-11-02', 'time': '18:00:00Z'}","{'date': '2024-11-02', 'time': '14:00:00Z'}"
21,2024,22,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,Las Vegas Grand Prix,"{'circuitId': 'vegas', 'url': 'https://en.wiki...",2024-11-23,06:00:00Z,"{'date': '2024-11-21', 'time': '02:30:00Z'}","{'date': '2024-11-21', 'time': '06:00:00Z'}","{'date': '2024-11-22', 'time': '02:30:00Z'}","{'date': '2024-11-22', 'time': '06:00:00Z'}",NaN
22,2024,23,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,Qatar Grand Prix,"{'circuitId': 'losail', 'url': 'http://en.wiki...",2024-12-01,17:00:00Z,"{'date': '2024-11-29', 'time': '13:30:00Z'}","{'date': '2024-11-29', 'time': '17:30:00Z'}",NaN,"{'date': '2024-11-30', 'time': '17:00:00Z'}","{'date': '2024-11-30', 'time': '13:00:00Z'}"
23,2024,24,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,Abu Dhabi Grand Prix,"{'circuitId': 'yas_marina', 'url': 'http://en....",2024-12-08,13:00:00Z,"{'date': '2024-12-06', 'time': '09:30:00Z'}","{'date': '2024-12-06', 'time': '13:00:00Z'}","{'date': '2024-12-07', 'time': '10:30:00Z'}","{'date': '2024-12-07', 'time': '14:00:00Z'}",NaN

In [140]:
season_list['date'] = pd.to_datetime(season_list['date']).dt.date
season_list['season'] = season_list['season'].astype('int')
season_list['round'] = season_list['round'].astype('int')

In [141]:
season_list.dtypes

season             int32
round              int32
url               object
raceName          object
Circuit           object
date              object
time              object
FirstPractice     object
SecondPractice    object
ThirdPractice     object
Qualifying        object
Sprint            object
dtype: object

In [128]:
season_list.head()

,season,round,url,raceName,Circuit,date,time,FirstPractice,SecondPractice,ThirdPractice,Qualifying,Sprint
0,2020,1,http://en.wikipedia.org/wiki/2020_Austrian_Gra...,Austrian Grand Prix,"{'circuitId': 'red_bull_ring', 'url': 'http://...",2020-07-05,13:10:00Z,NaN,NaN,NaN,NaN,NaN
1,2020,2,http://en.wikipedia.org/wiki/2020_Styrian_Gran...,Styrian Grand Prix,"{'circuitId': 'red_bull_ring', 'url': 'http://...",2020-07-12,13:10:00Z,NaN,NaN,NaN,NaN,NaN
2,2020,3,http://en.wikipedia.org/wiki/2020_Hungarian_Gr...,Hungarian Grand Prix,"{'circuitId': 'hungaroring', 'url': 'http://en...",2020-07-19,13:10:00Z,NaN,NaN,NaN,NaN,NaN
3,2020,4,http://en.wikipedia.org/wiki/2020_British_Gran...,British Grand Prix,"{'circuitId': 'silverstone', 'url': 'http://en...",2020-08-02,13:10:00Z,NaN,NaN,NaN,NaN,NaN
4,2020,5,http://en.wikipedia.org/wiki/70th_Anniversary_...,70th Anniversary Grand Prix,"{'circuitId': 'silverstone', 'url': 'http://en...",2020-08-09,13:10:00Z,NaN,NaN,NaN,NaN,NaN

In [112]:
filtered_date = season_list[(season_list['season']==current_year) & (season_list['date']<today)]
max_round_todate = filtered_date.loc[filtered_date['date'].idxmax()]['round']

NameError: name 'season_list' is not defined

In [110]:
# Race result
def get_race_result():
    print("getting race result...")
    race_result = pd.DataFrame()
    for year in range(start_year,current_year+1):
        if year < current_year:
            for race_no in range(1,25):
                url = f"http://ergast.com/api/f1/{year}/{race_no}/results.json"
                try:
                    response = requests.get(url)
                    response.raise_for_status()
                    if response.status_code != 204:
                        json_data = response.json()
                    df = pd.DataFrame(json_data['MRData']['RaceTable']['Races'][0]['Results'])
                    df['season'] = year
                    df['round'] = race_no
                except:
                    pass
                race_result = race_result._append(df)
        else:     
            for race_no in range(1,max_round_todate+1):
                url = f'http://ergast.com/api/f1/{year}/{race_no}/results.json'
                try:
                    response = re
                    quests.get(url)
                    response.raise_for_status()
                    if response.status_code != 204:
                        json_data = response.json()
                    df = pd.DataFrame(json_data['MRData']['RaceTable']['Races'][0]['Results']) 
                    df['season'] = year
                    df['round'] = race_no
                    race_result = race_result._append(df)
                except:
                    pass
    race_result.to_csv('race_result.csv')
    return race_result

In [113]:
max_round_todate = 2
get_race_result()

getting race result...

,number,position,positionText,points,Driver,Constructor,grid,laps,status,Time,FastestLap,season,round
0,1,1,1,25,"{'driverId': 'max_verstappen', 'permanentNumbe...","{'constructorId': 'red_bull', 'url': 'http://e...",1,57,Finished,"{'millis': '5636736', 'time': '1:33:56.736'}","{'rank': '6', 'lap': '44', 'Time': {'time': '1...",2023,1
1,11,2,2,18,"{'driverId': 'perez', 'permanentNumber': '11',...","{'constructorId': 'red_bull', 'url': 'http://e...",2,57,Finished,"{'millis': '5648723', 'time': '+11.987'}","{'rank': '7', 'lap': '37', 'Time': {'time': '1...",2023,1
2,14,3,3,15,"{'driverId': 'alonso', 'permanentNumber': '14'...","{'constructorId': 'aston_martin', 'url': 'http...",5,57,Finished,"{'millis': '5675373', 'time': '+38.637'}","{'rank': '5', 'lap': '36', 'Time': {'time': '1...",2023,1
3,55,4,4,12,"{'driverId': 'sainz', 'permanentNumber': '55',...","{'constructorId': 'ferrari', 'url': 'http://en...",4,57,Finished,"{'millis': '5684788', 'time': '+48.052'}","{'rank': '14', 'lap': '37', 'Time': {'time': '...",2023,1
4,44,5,5,10,"{'driverId': 'hamilton', 'permanentNumber': '4...","{'constructorId': 'mercedes', 'url': 'http://e...",7,57,Finished,"{'millis': '5687713', 'time': '+50.977'}","{'rank': '10', 'lap': '36', 'Time': {'time': '...",2023,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,2,16,16,0,"{'driverId': 'sargeant', 'permanentNumber': '2...","{'constructorId': 'williams', 'url': 'http://e...",20,58,Finished,"{'millis': '5310415', 'time': '+1:27.791'}","{'rank': '12', 'lap': '43', 'Time': {'time': '...",2023,22
16,24,17,17,0,"{'driverId': 'zhou', 'permanentNumber': '24', ...","{'constructorId': 'alfa', 'url': 'http://en.wi...",19,58,Finished,"{'millis': '5312046', 'time': '+1:29.422'}","{'rank': '13', 'lap': '43', 'Time': {'time': '...",2023,22
17,55,18,18,0,"{'driverId': 'sainz', 'permanentNumber': '55',...","{'constructorId': 'ferrari', 'url': 'http://en...",16,57,Retired,NaN,"{'rank': '17', 'lap': '42', 'Time': {'time': '...",2023,22
18,77,19,19,0,"{'driverId': 'bottas', 'permanentNumber': '77'...","{'constructorId': 'alfa', 'url': 'http://en.wi...",18,57,+1 Lap,NaN,"{'rank': '18', 'lap': '42', 'Time': {'time': '...",2023,22
19,20,20,20,0,"{'driverId': 'kevin_magnussen', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",17,57,+1 Lap,NaN,"{'rank': '19', 'lap': '46', 'Time': {'time': '...",2023,22

In [ ]:
class ErgastDataRetriever:
    def __init__(self):
        self.base_url = "http://ergast.com/api/f1"
        self.session_key = None

In [215]:
# Meeting info
def get_meeting_info(start_year,end_year):
    print("getting meeting info...")
    meeting_info = pd.DataFrame()
    for year in range(start_year,end_year+1):
        url = f'https://api.openf1.org/v1/meetings?year={year}'
        try:
            response = requests.get(url)
            response.raise_for_status()
            if response.status_code != 204:
                json_data = response.json()
            df = pd.DataFrame(json_data)
            meeting_info = meeting_info._append(df)
        except:
            pass
    return meeting_info

In [246]:
# Session info
def get_session_info(start_year,end_year):
    print("getting session info...")
    session_info = pd.DataFrame()
    for year in range(start_year,end_year+1):
        url = f"https://api.openf1.org/v1/sessions?session_name=Race&year={year}"
        try:
            response = requests.get(url)
            response.raise_for_status()
            if response.status_code != 204:
                json_data = response.json()
            df = pd.DataFrame(json_data)
            session_info = session_info._append(df)
        except:
            pass
    session_key_list = list(session_info['session_key'])
    return session_info, session_key_list

In [ ]:
session_info, session_key_list = get_session_info()

In [247]:
# Weather info
def get_weather_info():
    print("getting weather info...")
    session_info, session_key_list = get_session_info()
    weather_info = pd.DataFrame()
    for session in session_key_list:
        url = f"https://api.openf1.org/v1/weather?session_key={session}"
        try:
            response = requests.get(url)
            response.raise_for_status()
            if response.status_code != 204:
                json_data = response.json()
            df = pd.DataFrame(json_data)
            weather_info = weather_info._append(df)
        except:
            pass
    return weather_info

getting session info...

,air_temperature,humidity,pressure,rainfall,track_temperature,wind_direction,wind_speed,date,session_key,meeting_key
0,29.8,19.0,1016.5,0,35.1,176,1.2,2023-03-05T14:01:47.286000,7953,1141
1,29.7,19.0,1016.5,0,35.0,182,1.2,2023-03-05T14:02:47.301000,7953,1141
2,29.7,19.0,1016.5,0,34.9,156,1.1,2023-03-05T14:03:47.300000,7953,1141
3,29.6,19.0,1016.5,0,34.9,201,0.8,2023-03-05T14:04:47.314000,7953,1141
4,29.6,19.0,1016.5,0,34.8,219,0.8,2023-03-05T14:05:47.297000,7953,1141
...,...,...,...,...,...,...,...,...,...,...
141,25.3,66.0,1013.1,0,29.8,346,0.4,2024-03-09T18:25:24.062000,9480,1230
142,25.3,66.0,1013.1,0,29.8,0,1.0,2024-03-09T18:26:24.060000,9480,1230
143,25.3,66.0,1013.1,0,29.7,24,0.9,2024-03-09T18:27:24.077000,9480,1230
144,25.3,66.0,1013.2,0,29.1,320,1.2,2024-03-09T18:28:24.096000,9480,1230
145,25.2,67.0,1013.1,0,29.1,28,1.4,2024-03-09T18:29:24.088000,9480,1230

In [2]:
start_year = 2018
end_year = 2020
start_date = '2023-01-01'
end_date = '2024-03-10'

In [120]:
class DataRetriever:
    def __init__(self,start_year,end_year,start_date,end_date):
        self.start_year = start_year
        self.end_year = end_year
        self.start_date = start_date
        self.end_date = end_date
        self.today = date.today()
        self.current_year = date.today().year
    
    def _fetch_data(self,url):
        try:
            response = requests.get(url)
            response.raise_for_status()
            json_data = response.json()
            return json_data
        except requests.exceptions.HTTPError as e:
            return f"Error: {e}"
        except requests.exceptions.RequestException as f:
            return f"Error: {f}"

    
class Ergast(DataRetriever):

    def __init__(self,start_year,end_year,start_date,end_date):
        super().__init__(start_year,end_year,start_date,end_date)
        self.base_url = "http://ergast.com/api/f1"
        self.max_round_todate = None

    def get_season_list(self):
        season_list = []
        for year in range(self.start_year, self.end_year + 1):
            url = f"{self.base_url}/{year}.json"
            fetched = self._fetch_data(url)
            df = pd.DataFrame(fetched['MRData']['RaceTable']['Races'])
            season_list.append(df)
        
        combined_season_df = pd.concat(season_list, ignore_index=True)
        combined_season_df['date'] = pd.to_datetime(combined_season_df['date']).dt.date
        combined_season_df['season'] = combined_season_df['season'].astype('int')
        combined_season_df['round'] = combined_season_df['round'].astype('int')
        
        if self.max_round_todate is None:
            filtered_date = combined_season_df[(combined_season_df['season'] == self.current_year) & (combined_season_df['date'] < self.today)]
            
            if not filtered_date.empty:
                max_round = filtered_date.loc[filtered_date['date'].idxmax(), 'round']
                self.max_round_todate = max_round.astype('int')
            else:
                print("Filtered data is empty. No max round found.")
    
        combined_season_df.to_csv('season_list.csv', index=False)
        return combined_season_df
        
    def get_race_result(self):
        race_result = []
        for year in range(self.start_year,self.current_year+1):
            if year < self.current_year:
                for race_no in range(1,25):
                    url = f"{self.base_url}/{year}/{race_no}/results.json"
                    fetched = self._fetch_data(url)
                    if 'MRData' in fetched and 'RaceTable' in fetched['MRData'] and 'Races' in fetched['MRData']['RaceTable']:
                        race_data = fetched['MRData']['RaceTable']['Races']
                        if race_data:
                            df = pd.DataFrame(race_data[0]['Results'])
                            df['season'] = year
                            df['round'] = race_no
                            race_result.append(df)

            else:     
                for race_no in range(1,self.max_round_todate+1):
                    url = f"{self.base_url}/{year}/{race_no}/results.json"
                    fetched = self._fetch_data(url)
                    if 'MRData' in fetched and 'RaceTable' in fetched['MRData'] and 'Races' in fetched['MRData']['RaceTable']:
                        race_data = fetched['MRData']['RaceTable']['Races']
                        if race_data:
                            df = pd.DataFrame(race_data[0]['Results'])
                            df['season'] = year
                            df['round'] = race_no
                            race_result.append(df)
        
        combined_race_result = pd.concat(race_result,ignore_index=True)
        combined_race_result.to_csv('race_result.csv', index=False)
        return combined_race_result

In [121]:
ergast = Ergast(start_year,end_year,start_date,end_date)
ergast.get_season_list()
ergast.get_race_result()

,number,position,positionText,points,Driver,Constructor,grid,laps,status,Time,FastestLap,season,round
0,1,1,1,25,"{'driverId': 'max_verstappen', 'permanentNumbe...","{'constructorId': 'red_bull', 'url': 'http://e...",1,57,Finished,"{'millis': '5636736', 'time': '1:33:56.736'}","{'rank': '6', 'lap': '44', 'Time': {'time': '1...",2023,1
1,11,2,2,18,"{'driverId': 'perez', 'permanentNumber': '11',...","{'constructorId': 'red_bull', 'url': 'http://e...",2,57,Finished,"{'millis': '5648723', 'time': '+11.987'}","{'rank': '7', 'lap': '37', 'Time': {'time': '1...",2023,1
2,14,3,3,15,"{'driverId': 'alonso', 'permanentNumber': '14'...","{'constructorId': 'aston_martin', 'url': 'http...",5,57,Finished,"{'millis': '5675373', 'time': '+38.637'}","{'rank': '5', 'lap': '36', 'Time': {'time': '1...",2023,1
3,55,4,4,12,"{'driverId': 'sainz', 'permanentNumber': '55',...","{'constructorId': 'ferrari', 'url': 'http://en...",4,57,Finished,"{'millis': '5684788', 'time': '+48.052'}","{'rank': '14', 'lap': '37', 'Time': {'time': '...",2023,1
4,44,5,5,10,"{'driverId': 'hamilton', 'permanentNumber': '4...","{'constructorId': 'mercedes', 'url': 'http://e...",7,57,Finished,"{'millis': '5687713', 'time': '+50.977'}","{'rank': '10', 'lap': '36', 'Time': {'time': '...",2023,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,3,16,16,0,"{'driverId': 'ricciardo', 'permanentNumber': '...","{'constructorId': 'rb', 'url': 'http://en.wiki...",14,49,+1 Lap,NaN,"{'rank': '16', 'lap': '47', 'Time': {'time': '...",2024,2
476,77,17,17,0,"{'driverId': 'bottas', 'permanentNumber': '77'...","{'constructorId': 'sauber', 'url': 'http://en....",16,49,+1 Lap,NaN,"{'rank': '14', 'lap': '49', 'Time': {'time': '...",2024,2
477,24,18,18,0,"{'driverId': 'zhou', 'permanentNumber': '24', ...","{'constructorId': 'sauber', 'url': 'http://en....",20,49,+1 Lap,NaN,"{'rank': '6', 'lap': '49', 'Time': {'time': '1...",2024,2
478,18,19,R,0,"{'driverId': 'stroll', 'permanentNumber': '18'...","{'constructorId': 'aston_martin', 'url': 'http...",10,5,Accident,NaN,"{'rank': '19', 'lap': '5', 'Time': {'time': '1...",2024,2
479,10,20,R,0,"{'driverId': 'gasly', 'permanentNumber': '10',...","{'constructorId': 'alpine', 'url': 'http://en....",18,1,Gearbox,NaN,NaN,2024,2

In [100]:
url = "http://ergast.com/api/f1/2008/5/results.json"
response = requests.get(url)
response.raise_for_status()
json_data = response.json()
sliced = fetched['MRData']['RaceTable']['Races'][0]['Results']
df = pd.DataFrame(sliced)
# df = pd.DataFrame(json_data['MRData']['RaceTable']['Races']#['Results'])
df

[{'number': '2',
  'position': '1',
  'positionText': '1',
  'points': '10',
  'Driver': {'driverId': 'massa',
   'permanentNumber': '19',
   'code': 'MAS',
   'url': 'http://en.wikipedia.org/wiki/Felipe_Massa',
   'givenName': 'Felipe',
   'familyName': 'Massa',
   'dateOfBirth': '1981-04-25',
   'nationality': 'Brazilian'},
  'Constructor': {'constructorId': 'ferrari',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
   'name': 'Ferrari',
   'nationality': 'Italian'},
  'grid': '1',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5209451', 'time': '1:26:49.451'},
  'FastestLap': {'rank': '3',
   'lap': '16',
   'Time': {'time': '1:26.666'},
   'AverageSpeed': {'units': 'kph', 'speed': '221.734'}}},
 {'number': '22',
  'position': '2',
  'positionText': '2',
  'points': '8',
  'Driver': {'driverId': 'hamilton',
   'permanentNumber': '44',
   'code': 'HAM',
   'url': 'http://en.wikipedia.org/wiki/Lewis_Hamilton',
   'givenName': 'Lewis',
   'familyName': 'Hamilton',
   'dateOfBirth': '1985-01-07',
   'nationality': 'British'},
  'Constructor': {'constructorId': 'mclaren',
   'url': 'http://en.wikipedia.org/wiki/McLaren',
   'name': 'McLaren',
   'nationality': 'British'},
  'grid': '3',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5213230', 'time': '+3.779'},
  'FastestLap': {'rank': '2',
   'lap': '31',
   'Time': {'time': '1:26.529'},
   'AverageSpeed': {'units': 'kph', 'speed': '222.085'}}},
 {'number': '1',
  'position': '3',
  'positionText': '3',
  'points': '6',
  'Driver': {'driverId': 'raikkonen',
   'permanentNumber': '7',
   'code': 'RAI',
   'url': 'http://en.wikipedia.org/wiki/Kimi_R%C3%A4ikk%C3%B6nen',
   'givenName': 'Kimi',
   'familyName': 'Räikkönen',
   'dateOfBirth': '1979-10-17',
   'nationality': 'Finnish'},
  'Constructor': {'constructorId': 'ferrari',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
   'name': 'Ferrari',
   'nationality': 'Italian'},
  'grid': '4',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5213722', 'time': '+4.271'},
  'FastestLap': {'rank': '1',
   'lap': '20',
   'Time': {'time': '1:26.506'},
   'AverageSpeed': {'units': 'kph', 'speed': '222.144'}}},
 {'number': '4',
  'position': '4',
  'positionText': '4',
  'points': '5',
  'Driver': {'driverId': 'kubica',
   'permanentNumber': '88',
   'code': 'KUB',
   'url': 'http://en.wikipedia.org/wiki/Robert_Kubica',
   'givenName': 'Robert',
   'familyName': 'Kubica',
   'dateOfBirth': '1984-12-07',
   'nationality': 'Polish'},
  'Constructor': {'constructorId': 'bmw_sauber',
   'url': 'http://en.wikipedia.org/wiki/BMW_Sauber',
   'name': 'BMW Sauber',
   'nationality': 'German'},
  'grid': '5',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5231396', 'time': '+21.945'},
  'FastestLap': {'rank': '4',
   'lap': '17',
   'Time': {'time': '1:26.780'},
   'AverageSpeed': {'units': 'kph', 'speed': '221.442'}}},
 {'number': '3',
  'position': '5',
  'positionText': '5',
  'points': '4',
  'Driver': {'driverId': 'heidfeld',
   'code': 'HEI',
   'url': 'http://en.wikipedia.org/wiki/Nick_Heidfeld',
   'givenName': 'Nick',
   'familyName': 'Heidfeld',
   'dateOfBirth': '1977-05-10',
   'nationality': 'German'},
  'Constructor': {'constructorId': 'bmw_sauber',
   'url': 'http://en.wikipedia.org/wiki/BMW_Sauber',
   'name': 'BMW Sauber',
   'nationality': 'German'},
  'grid': '9',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5248192', 'time': '+38.741'},
  'FastestLap': {'rank': '5',
   'lap': '20',
   'Time': {'time': '1:27.219'},
   'AverageSpeed': {'units': 'kph', 'speed': '220.328'}}},
 {'number': '5',
  'position': '6',
  'positionText': '6',
  'points': '3',
  'Driver': {'driverId': 'alonso',
   'permanentNumber': '14',
   'code': 'ALO',
   'url': 'http://en.wikipedia.org/wiki/Fernando_Alonso',
   'givenName': 'Fernando',
   'familyName': 'Alonso',
   'dateOfBirth': '1981-07-29',
   'nationality': 'Spanish'},
  'Constructor': {'constructorId': 'renault',
   'url': 'http://en.wikipedia.org/wiki/Renault_in_Formula_One',
   'name': 'Renault',
   'nationality': 'French'},
  'grid': '7',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5263175', 'time': '+53.724'},
  'FastestLap': {'rank': '6',
   'lap': '57',
   'Time': {'time': '1:27.280'},
   'AverageSpeed': {'units': 'kph', 'speed': '220.174'}}},
 {'number': '10',
  'position': '7',
  'positionText': '7',
  'points': '2',
  'Driver': {'driverId': 'webber',
   'code': 'WEB',
   'url': 'http://en.wikipedia.org/wiki/Mark_Webber_(racing_driver)',
   'givenName': 'Mark',
   'familyName': 'Webber',
   'dateOfBirth': '1976-08-27',
   'nationality': 'Australian'},
  'Constructor': {'constructorId': 'red_bull',
   'url': 'http://en.wikipedia.org/wiki/Red_Bull_Racing',
   'name': 'Red Bull',
   'nationality': 'Austrian'},
  'grid': '6',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5273680', 'time': '+1:04.229'},
  'FastestLap': {'rank': '7',
   'lap': '14',
   'Time': {'time': '1:27.630'},
   'AverageSpeed': {'units': 'kph', 'speed': '219.294'}}},
 {'number': '7',
  'position': '8',
  'positionText': '8',
  'points': '1',
  'Driver': {'driverId': 'rosberg',
   'permanentNumber': '6',
   'code': 'ROS',
   'url': 'http://en.wikipedia.org/wiki/Nico_Rosberg',
   'givenName': 'Nico',
   'familyName': 'Rosberg',
   'dateOfBirth': '1985-06-27',
   'nationality': 'German'},
  'Constructor': {'constructorId': 'williams',
   'url': 'http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering',
   'name': 'Williams',
   'nationality': 'British'},
  'grid': '11',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5280857', 'time': '+1:11.406'},
  'FastestLap': {'rank': '9',
   'lap': '55',
   'Time': {'time': '1:27.795'},
   'AverageSpeed': {'units': 'kph', 'speed': '218.882'}}},
 {'number': '9',
  'position': '9',
  'positionText': '9',
  'points': '0',
  'Driver': {'driverId': 'coulthard',
   'code': 'COU',
   'url': 'http://en.wikipedia.org/wiki/David_Coulthard',
   'givenName': 'David',
   'familyName': 'Coulthard',
   'dateOfBirth': '1971-03-27',
   'nationality': 'British'},
  'Constructor': {'constructorId': 'red_bull',
   'url': 'http://en.wikipedia.org/wiki/Red_Bull_Racing',
   'name': 'Red Bull',
   'nationality': 'Austrian'},
  'grid': '10',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5284721', 'time': '+1:15.270'},
  'FastestLap': {'rank': '12',
   'lap': '41',
   'Time': {'time': '1:27.966'},
   'AverageSpeed': {'units': 'kph', 'speed': '218.457'}}},
 {'number': '11',
  'position': '10',
  'positionText': '10',
  'points': '0',
  'Driver': {'driverId': 'trulli',
   'code': 'TRU',
   'url': 'http://en.wikipedia.org/wiki/Jarno_Trulli',
   'givenName': 'Jarno',
   'familyName': 'Trulli',
   'dateOfBirth': '1974-07-13',
   'nationality': 'Italian'},
  'Constructor': {'constructorId': 'toyota',
   'url': 'http://en.wikipedia.org/wiki/Toyota_Racing',
   'name': 'Toyota',
   'nationality': 'Japanese'},
  'grid': '8',
  'laps': '58',
  'status': 'Finished',
  'Time': {'millis': '5285795', 'time': '+1:16.344'},
  'FastestLap': {'rank': '11',
   'lap': '52',
   'Time': {'time': '1:27.926'},
   'AverageSpeed': {'units': 'kph', 'speed': '218.556'}}},
 {'number': '16',
  'position': '11',
  'positionText': '11',
  'points': '0',
  'Driver': {'driverId': 'button',
   'permanentNumber': '22',
   'code': 'BUT',
   'url': 'http://en.wikipedia.org/wiki/Jenson_Button',
   'givenName': 'Jenson',
   'familyName': 'Button',
   'dateOfBirth': '1980-01-19',
   'nationality': 'British'},
  'Constructor': {'constructorId': 'honda',
   'url': 'http://en.wikipedia.org/wiki/Honda_Racing_F1',
   'name': 'Honda',
   'nationality': 'Japanese'},
  'grid': '13',
  'laps': '57',
  'status': '+1 Lap',
  'FastestLap': {'rank': '13',
   'lap': '57',
   'Time': {'time': '1:27.998'},
   'AverageSpeed': {'units': 'kph', 'speed': '218.377'}}},
 {'number': '23',
  'position': '12',
  'positionText': '12',
  'points': '0',
  'Driver': {'driverId': 'kovalainen',
   'code': 'KOV',
   'url': 'http://en.wikipedia.org/wiki/Heikki_Kovalainen',
   'givenName': 'Heikki',
   'familyName': 'Kovalainen',
   'dateOfBirth': '1981-10-19',
   'nationality': 'Finnish'},
  'Constructor': {'constructorId': 'mclaren',
   'url': 'http://en.wikipedia.org/wiki/McLaren',
   'name': 'McLaren',
   'nationality': 'British'},
  'grid': '2',
  'laps': '57',
  'status': '+1 Lap',
  'FastestLap': {'rank': '8',
   'lap': '55',
   'Time': {'time': '1:27.640'},
   'AverageSpeed': {'units': 'kph', 'speed': '219.269'}}},
 {'number': '12',
  'position': '13',
  'positionText': '13',
  'points': '0',
  'Driver': {'driverId': 'glock',
   'code': 'GLO',
   'url': 'http://en.wikipedia.org/wiki/Timo_Glock',
   'givenName': 'Timo',
   'familyName': 'Glock',
   'dateOfBirth': '1982-03-18',
   'nationality': 'German'},
  'Constructor': {'constructorId': 'toyota',
   'url': 'http://en.wikipedia.org/wiki/Toyota_Racing',
   'name': 'Toyota',
   'nationality': 'Japanese'},
  'grid': '15',
  'laps': '57',
  'status': '+1 Lap',
  'FastestLap': {'rank': '16',
   'lap': '28',
   'Time': {'time': '1:28.303'},
   'AverageSpeed': {'units': 'kph', 'speed': '217.623'}}},
 {'number': '17',
  'position': '14',
  'positionText': '14',
  'points': '0',
  'Driver': {'driverId': 'barrichello',
   'code': 'BAR',
   'url': 'http://en.wikipedia.org/wiki/Rubens_Barrichello',
   'givenName': 'Rubens',
   'familyName': 'Barrichello',
   'dateOfBirth': '1972-05-23',
   'nationality': 'Brazilian'},
  'Constructor': {'constructorId': 'honda',
   'url': 'http://en.wikipedia.org/wiki/Honda_Racing_F1',
   'name': 'Honda',
   'nationality': 'Japanese'},
  'grid': '12',
  'laps': '57',
  'status': '+1 Lap',
  'FastestLap': {'rank': '14',
   'lap': '56',
   'Time': {'time': '1:28.017'},
   'AverageSpeed': {'units': 'kph', 'speed': '218.330'}}},
 {'number': '6',
  'position': '15',
  'positionText': '15',
  'points': '0',
  'Driver': {'driverId': 'piquet_jr',
   'code': 'PIQ',
   'url': 'http://en.wikipedia.org/wiki/Nelson_Piquet,_Jr.',
   'givenName': 'Nelson',
   'familyName': 'Piquet Jr.',
   'dateOfBirth': '1985-07-25',
   'nationality': 'Brazilian'},
  'Constructor': {'constructorId': 'renault',
   'url': 'http://en.wikipedia.org/wiki/Renault_in_Formula_One',
   'name': 'Renault',
   'nationality': 'French'},
  'grid': '17',
  'laps': '57',
  'status': '+1 Lap',
  'FastestLap': {'rank': '10',
   'lap': '40',
   'Time': {'time': '1:27.867'},
   'AverageSpeed': {'units': 'kph', 'speed': '218.703'}}},
 {'number': '20',
  'position': '16',
  'positionText': '16',
  'points': '0',
  'Driver': {'driverId': 'sutil',
   'permanentNumber': '99',
   'code': 'SUT',
   'url': 'http://en.wikipedia.org/wiki/Adrian_Sutil',
   'givenName': 'Adrian',
   'familyName': 'Sutil',
   'dateOfBirth': '1983-01-11',
   'nationality': 'German'},
  'Constructor': {'constructorId': 'force_india',
   'url': 'http://en.wikipedia.org/wiki/Racing_Point_Force_India',
   'name': 'Force India',
   'nationality': 'Indian'},
  'grid': '19',
  'laps': '57',
  'status': '+1 Lap',
  'FastestLap': {'rank': '18',
   'lap': '35',
   'Time': {'time': '1:28.780'},
   'AverageSpeed': {'units': 'kph', 'speed': '216.454'}}},
 {'number': '15',
  'position': '17',
  'positionText': '17',
  'points': '0',
  'Driver': {'driverId': 'vettel',
   'permanentNumber': '5',
   'code': 'VET',
   'url': 'http://en.wikipedia.org/wiki/Sebastian_Vettel',
   'givenName': 'Sebastian',
   'familyName': 'Vettel',
   'dateOfBirth': '1987-07-03',
   'nationality': 'German'},
  'Constructor': {'constructorId': 'toro_rosso',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso',
   'name': 'Toro Rosso',
   'nationality': 'Italian'},
  'grid': '14',
  'laps': '57',
  'status': '+1 Lap',
  'FastestLap': {'rank': '15',
   'lap': '38',
   'Time': {'time': '1:28.180'},
   'AverageSpeed': {'units': 'kph', 'speed': '217.926'}}},
 {'number': '14',
  'position': '18',
  'positionText': 'R',
  'points': '0',
  'Driver': {'driverId': 'bourdais',
   'code': 'BOU',
   'url': 'http://en.wikipedia.org/wiki/S%C3%A9bastien_Bourdais',
   'givenName': 'Sébastien',
   'familyName': 'Bourdais',
   'dateOfBirth': '1979-02-28',
   'nationality': 'French'},
  'Constructor': {'constructorId': 'toro_rosso',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso',
   'name': 'Toro Rosso',
   'nationality': 'Italian'},
  'grid': '18',
  'laps': '24',
  'status': 'Suspension',
  'FastestLap': {'rank': '17',
   'lap': '19',
   'Time': {'time': '1:28.745'},
   'AverageSpeed': {'units': 'kph', 'speed': '216.539'}}},
 {'number': '8',
  'position': '19',
  'positionText': 'R',
  'points': '0',
  'Driver': {'driverId': 'nakajima',
   'code': 'NAK',
   'url': 'http://en.wikipedia.org/wiki/Kazuki_Nakajima',
   'givenName': 'Kazuki',
   'familyName': 'Nakajima',
   'dateOfBirth': '1985-01-11',
   'nationality': 'Japanese'},
  'Constructor': {'constructorId': 'williams',
   'url': 'http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering',
   'name': 'Williams',
   'nationality': 'British'},
  'grid': '16',
  'laps': '1',
  'status': 'Collision'},
 {'number': '21',
  'position': '20',
  'positionText': 'R',
  'points': '0',
  'Driver': {'driverId': 'fisichella',
   'code': 'FIS',
   'url': 'http://en.wikipedia.org/wiki/Giancarlo_Fisichella',
   'givenName': 'Giancarlo',
   'familyName': 'Fisichella',
   'dateOfBirth': '1973-01-14',
   'nationality': 'Italian'},
  'Constructor': {'constructorId': 'force_india',
   'url': 'http://en.wikipedia.org/wiki/Racing_Point_Force_India',
   'name': 'Force India',
   'nationality': 'Indian'},
  'grid': '20',
  'laps': '0',
  'status': 'Collision'}]

In [123]:
openf1.get_meeting_info()

,meeting_name,meeting_official_name,location,country_key,country_code,country_name,circuit_key,circuit_short_name,date_start,gmt_offset,meeting_key,year,meeting_code
0,Pre-Season Testing,FORMULA 1 ARAMCO PRE-SEASON TESTING 2023,Sakhir,36,BRN,Bahrain,63,Sakhir,2023-02-23T07:00:00,03:00:00,1140,2023,NaN
1,Bahrain Grand Prix,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023,Sakhir,36,BRN,Bahrain,63,Sakhir,2023-03-03T11:30:00,03:00:00,1141,2023,NaN
2,Saudi Arabian Grand Prix,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2023,Jeddah,153,KSA,Saudi Arabia,149,Jeddah,2023-03-17T13:30:00,03:00:00,1142,2023,NaN
3,Australian Grand Prix,FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2023,Melbourne,5,AUS,Australia,10,Melbourne,2023-03-31T01:30:00,11:00:00,1143,2023,NaN
4,Azerbaijan Grand Prix,FORMULA 1 AZERBAIJAN GRAND PRIX 2023,Baku,30,AZE,Azerbaijan,144,Baku,2023-04-28T09:30:00,04:00:00,1207,2023,NaN
5,Miami Grand Prix,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2023,Miami,19,USA,United States,151,Miami,2023-05-05T18:00:00,-04:00:00,1208,2023,NaN
6,Monaco Grand Prix,FORMULA 1 GRAND PRIX DE MONACO 2023,Monaco,114,MON,Monaco,22,Monte Carlo,2023-05-26T11:30:00,02:00:00,1210,2023,NaN
7,Spanish Grand Prix,FORMULA 1 AWS GRAN PREMIO DE ESPAÑA 2023,Barcelona,1,ESP,Spain,15,Catalunya,2023-06-02T11:30:00,02:00:00,1211,2023,NaN
8,Canadian Grand Prix,FORMULA 1 PIRELLI GRAND PRIX DU CANADA 2023,Montréal,46,CAN,Canada,23,Montreal,2023-06-16T17:30:00,-04:00:00,1212,2023,NaN
9,Austrian Grand Prix,FORMULA 1 ROLEX GROSSER PREIS VON ÖSTERREICH 2023,Spielberg,17,AUT,Austria,19,Spielberg,2023-06-30T15:00:00,02:00:00,1213,2023,AUT
10,British Grand Prix,FORMULA 1 ARAMCO BRITISH GRAND PRIX 2023,Silverstone,2,GBR,Great Britain,2,Silverstone,2023-07-07T11:30:00,01:00:00,1214,2023,NaN
11,Hungarian Grand Prix,FORMULA 1 QATAR AIRWAYS HUNGARIAN GRAND PRIX 2023,Budapest,14,HUN,Hungary,4,Hungaroring,2023-07-21T11:30:00,02:00:00,1215,2023,NaN
12,Belgian Grand Prix,FORMULA 1 MSC CRUISES BELGIAN GRAND PRIX 2023,Spa-Francorchamps,16,BEL,Belgium,7,Spa-Francorchamps,2023-07-28T11:30:00,02:00:00,1216,2023,NaN
13,Dutch Grand Prix,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2023,Zandvoort,133,NED,Netherlands,55,Zandvoort,2023-08-25T10:30:00,02:00:00,1217,2023,NaN
14,Italian Grand Prix,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2023,Monza,13,ITA,Italy,39,Monza,2023-09-01T11:30:00,02:00:00,1218,2023,NaN
15,Singapore Grand Prix,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,Marina Bay,157,SGP,Singapore,61,Singapore,2023-09-15T09:30:00,08:00:00,1219,2023,NaN
16,Japanese Grand Prix,FORMULA 1 LENOVO JAPANESE GRAND PRIX 2023,Suzuka,4,JPN,Japan,46,Suzuka,2023-09-22T02:30:00,09:00:00,1220,2023,NaN
17,Qatar Grand Prix,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2023,Lusail,149,QAT,Qatar,150,Lusail,2023-10-06T13:30:00,03:00:00,1221,2023,NaN
18,United States Grand Prix,FORMULA 1 LENOVO UNITED STATES GRAND PRIX 2023,Austin,19,USA,United States,9,Austin,2023-10-20T17:30:00,-05:00:00,1222,2023,NaN
19,Mexico City Grand Prix,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2023,Mexico City,8,MEX,Mexico,65,Mexico City,2023-10-27T18:30:00,-06:00:00,1223,2023,NaN
20,São Paulo Grand Prix,FORMULA 1 ROLEX GRANDE PRÊMIO DE SÃO PAULO 2023,São Paulo,10,BRA,Brazil,14,Interlagos,2023-11-03T14:30:00,-03:00:00,1224,2023,NaN
21,Las Vegas Grand Prix,FORMULA 1 HEINEKEN SILVER LAS VEGAS GRAND PRIX...,Las Vegas,19,USA,United States,152,Las Vegas,2023-11-17T04:30:00,-08:00:00,1225,2023,NaN
22,Abu Dhabi Grand Prix,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,Yas Island,21,UAE,United Arab Emirates,70,Yas Marina Circuit,2023-11-24T09:30:00,04:00:00,1226,2023,NaN
23,Bahrain Grand Prix,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024,Sakhir,36,BRN,Bahrain,63,Sakhir,2024-02-29T11:30:00,03:00:00,1229,2024,BRN
24,Saudi Arabian Grand Prix,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2024,Jeddah,153,KSA,Saudi Arabia,149,Jeddah,2024-03-07T13:30:00,03:00:00,1230,2024,KSA

In [124]:
openf1.get_session_info()

,location,country_key,country_code,country_name,circuit_key,circuit_short_name,session_type,session_name,date_start,date_end,gmt_offset,session_key,meeting_key,year
0,Sakhir,36,BRN,Bahrain,63,Sakhir,Race,Race,2023-03-05T15:00:00,2023-03-05T17:00:00,03:00:00,7953,1141,2023
1,Jeddah,153,KSA,Saudi Arabia,149,Jeddah,Race,Race,2023-03-19T17:00:00,2023-03-19T19:00:00,03:00:00,7779,1142,2023
2,Melbourne,5,AUS,Australia,10,Melbourne,Race,Race,2023-04-02T05:00:00,2023-04-02T07:00:00,10:00:00,7787,1143,2023
3,Baku,30,AZE,Azerbaijan,144,Baku,Race,Race,2023-04-30T11:00:00,2023-04-30T13:00:00,04:00:00,9070,1207,2023
4,Miami,19,USA,United States,151,Miami,Race,Race,2023-05-07T19:30:00,2023-05-07T21:30:00,-04:00:00,9078,1208,2023
5,Monaco,114,MON,Monaco,22,Monte Carlo,Race,Race,2023-05-28T13:00:00,2023-05-28T15:00:00,02:00:00,9094,1210,2023
6,Barcelona,1,ESP,Spain,15,Catalunya,Race,Race,2023-06-04T13:00:00,2023-06-04T15:00:00,02:00:00,9102,1211,2023
7,Montréal,46,CAN,Canada,23,Montreal,Race,Race,2023-06-18T18:00:00,2023-06-18T20:00:00,-04:00:00,9110,1212,2023
8,Spielberg,17,AUT,Austria,19,Spielberg,Race,Race,2023-07-02T13:00:00,2023-07-02T15:00:00,02:00:00,9118,1213,2023
9,Silverstone,2,GBR,Great Britain,2,Silverstone,Race,Race,2023-07-09T14:00:00,2023-07-09T16:00:00,01:00:00,9126,1214,2023
10,Budapest,14,HUN,Hungary,4,Hungaroring,Race,Race,2023-07-23T13:00:00,2023-07-23T15:00:00,02:00:00,9133,1215,2023
11,Spa-Francorchamps,16,BEL,Belgium,7,Spa-Francorchamps,Race,Race,2023-07-30T13:00:00,2023-07-30T15:00:00,02:00:00,9141,1216,2023
12,Zandvoort,133,NED,Netherlands,55,Zandvoort,Race,Race,2023-08-27T13:00:00,2023-08-27T15:00:00,02:00:00,9149,1217,2023
13,Monza,13,ITA,Italy,39,Monza,Race,Race,2023-09-03T13:00:00,2023-09-03T15:00:00,02:00:00,9157,1218,2023
14,Marina Bay,157,SGP,Singapore,61,Singapore,Race,Race,2023-09-17T12:00:00,2023-09-17T14:00:00,08:00:00,9165,1219,2023
15,Suzuka,4,JPN,Japan,46,Suzuka,Race,Race,2023-09-24T05:00:00,2023-09-24T07:00:00,09:00:00,9173,1220,2023
16,Lusail,149,QAT,Qatar,150,Lusail,Race,Race,2023-10-08T17:00:00,2023-10-08T19:00:00,03:00:00,9221,1221,2023
17,Austin,19,USA,United States,9,Austin,Race,Race,2023-10-22T19:00:00,2023-10-22T21:00:00,-05:00:00,9213,1222,2023
18,Mexico City,8,MEX,Mexico,65,Mexico City,Race,Race,2023-10-29T20:00:00,2023-10-29T22:00:00,-06:00:00,9181,1223,2023
19,São Paulo,10,BRA,Brazil,14,Interlagos,Race,Race,2023-11-05T17:00:00,2023-11-05T19:00:00,-03:00:00,9205,1224,2023
20,Las Vegas,19,USA,United States,152,Las Vegas,Race,Race,2023-11-19T06:00:00,2023-11-19T08:00:00,-08:00:00,9189,1225,2023
21,Yas Island,21,UAE,United Arab Emirates,70,Yas Marina Circuit,Race,Race,2023-11-26T13:00:00,2023-11-26T15:00:00,04:00:00,9197,1226,2023
22,Sakhir,36,BRN,Bahrain,63,Sakhir,Race,Race,2024-03-02T15:00:00,2024-03-02T17:00:00,03:00:00,9472,1229,2024
23,Jeddah,153,KSA,Saudi Arabia,149,Jeddah,Race,Race,2024-03-09T17:00:00,2024-03-09T19:00:00,03:00:00,9480,1230,2024

In [125]:
openf1.get_weather_info()

,meeting_key,session_key,date,air_temperature,humidity,pressure,rainfall,track_temperature,wind_direction,wind_speed
0,1229,9472,2024-03-02T14:03:56.523000,18.9,46.0,1017.1,0,26.5,162,0.9
1,1229,9472,2024-03-02T14:04:56.514000,18.9,46.0,1017.0,0,26.5,55,1.0
2,1229,9472,2024-03-02T14:05:56.523000,18.9,46.0,1017.0,0,26.5,55,1.0
3,1229,9472,2024-03-02T14:06:56.520000,18.9,45.0,1017.0,0,26.2,85,1.1
4,1229,9472,2024-03-02T14:07:56.521000,18.9,46.0,1017.0,0,26.2,178,1.0
...,...,...,...,...,...,...,...,...,...,...
3916,1222,9213,2023-10-22T20:44:47.903000,30.6,43.0,992.9,0,39.3,108,2.5
3917,1222,9213,2023-10-22T20:45:47.902000,30.6,42.0,992.7,0,39.0,82,2.9
3918,1222,9213,2023-10-22T20:46:47.917000,30.6,43.0,992.7,0,39.7,95,4.1
3919,1222,9213,2023-10-22T20:47:47.916000,30.6,43.0,992.7,0,39.9,76,2.7
3920,1222,9213,2023-10-22T20:48:47.915000,30.6,43.0,992.5,0,39.7,82,2.4

In [126]:
openf1.get_laps_data()

,meeting_key,session_key,driver_number,i1_speed,i2_speed,st_speed,date_start,lap_duration,is_pit_out_lap,duration_sector_1,duration_sector_2,duration_sector_3,segments_sector_1,segments_sector_2,segments_sector_3,lap_number
0,1229,9472,1,234.0,250.0,251.0,None,NaN,False,NaN,41.266,23.616,"[2064, 2048, 2049, 2049, 2051, 2051, 2049, 204...","[2051, 2051, 2051, 2049, 2049, 2049, 2049, 205...","[2048, 2048, 2048, 2049, 2048, 2048, 2049]",1
1,1229,9472,2,230.0,249.0,231.0,None,NaN,False,NaN,43.162,24.178,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2048, 2049, 2048, 0]",1
2,1229,9472,3,233.0,241.0,257.0,None,NaN,False,NaN,43.159,24.451,"[2064, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2048, 2049, 2049, 2049]",1
3,1229,9472,4,233.0,247.0,237.0,None,NaN,False,NaN,43.309,24.244,"[2064, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2051, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2049, 2049, 2049, 2049]",1
4,1229,9472,10,231.0,246.0,272.0,None,NaN,False,NaN,43.704,24.393,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2049, 2049, 2048, 2049, 2049, 2049]",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26448,1222,9213,23,210.0,182.0,306.0,2023-10-22T20:38:42.113000,102.791,False,27.417,41.044,34.330,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56
26449,1222,9213,27,211.0,183.0,302.0,2023-10-22T20:38:50.175000,102.927,False,27.534,41.125,34.268,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56
26450,1222,9213,44,NaN,186.0,302.0,2023-10-22T20:37:24.802000,100.743,False,26.818,40.181,33.744,"[None, 2048, 2048, 2048, 2048, 2049]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2064, 2064]",56
26451,1222,9213,55,218.0,186.0,309.0,2023-10-22T20:37:37.192000,101.178,False,27.191,40.433,33.554,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2064, 2064]",56
26452,1222,9213,77,205.0,183.0,298.0,2023-10-22T20:38:58.113000,103.696,False,27.811,41.537,34.348,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56

In [46]:
import requests
import pandas as pd
from datetime import date

class DataRetriever:
    def __init__(self, start_year, end_year, start_date, end_date):
        self.start_year = start_year
        self.end_year = end_year
        self.start_date = start_date
        self.end_date = end_date
        self.today = date.today()
        self.current_year = self.today.year

    def _fetch_data(self, url):
        try:
            response = requests.get(url)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            return f"Error: {e}"

class Ergast(DataRetriever):
    def __init__(self, start_year, end_year, start_date, end_date):
        super().__init__(start_year, end_year, start_date, end_date)
        self.base_url = "http://ergast.com/api/f1"
        self.max_round_todate = None

    def get_season_list(self):
        season_list = pd.DataFrame()
        for year in range(self.start_year, self.end_year + 1):
            url = f"{self.base_url}/{year}.json"
            fetched = self._fetch_data(url)
            df = pd.DataFrame(fetched['MRData']['RaceTable']['Races'])
            season_list = season_list.append(df)
        return season_list

    def get_race_result(self):
        race_result = pd.DataFrame()
        for year in range(self.start_year, self.current_year + 1):
            if year < self.current_year:
                for race_no in range(1, 25):
                    url = f"{self.base_url}/{year}/{race_no}/results.json"
                    fetched = self._fetch_data(url)
                    df = pd.DataFrame(fetched['MRData']['RaceTable']['Races'][0]['Results'])
                    df['season'] = year
                    df['round'] = race_no
                    race_result = race_result.append(df)
            else:
                for race_no in range(1, self.max_round_todate + 1):
                    url = f"{self.base_url}/{year}/{race_no}/results.json"
                    fetched = self._fetch_data(url)
                    df = pd.DataFrame(fetched['MRData']['RaceTable']['Races'][0]['Results'])
                    df['season'] = year
                    df['round'] = race_no
                    race_result = race_result.append(df)
        return race_result

class OpenF1(DataRetriever):
    def __init__(self, start_year, end_year, start_date, end_date):
        super().__init__(start_year, end_year, start_date, end_date)
        self.base_url = "https://api.openf1.org/v1"
        self.session_key = None

    def get_meeting_info(self):
        url = f"{self.base_url}/meetings?year>={self.start_year}&year<={self.end_year}"
        fetched = self._fetch_data(url)
        return pd.DataFrame(fetched)

    def get_session_info(self):
        url = f"{self.base_url}/sessions?session_name=Race&date_start>={self.start_date}&date_end<={self.end_date}"
        fetched = self._fetch_data(url)
        session_info = pd.DataFrame(fetched)
        if self.session_key is None and not session_info.empty:
            self.session_key = list(set(session_info['session_key']))
        return session_info

    def get_weather_info(self):
        weather_info = pd.DataFrame()
        try:
            for session in self.session_key:
                url = f"{self.base_url}/weather?session_key={session}"
                fetched = self._fetch_data(url)
                weather_info = weather_info.append(fetched, ignore_index=True)
            return weather_info
        except Exception as e:
            return f"Error: {e}, session info is empty."

def get_laps_data(self):
            laps_data = pd.DataFrame()
            try:
                # pull data only from related session keys (race sessions)
                for session in self.session_key:
                    url = f"{self.base_url}/laps?session_key={session}"
                    fetched = self._fetch_data(url)
                    laps_data = laps_data._append(fetched,ignore_index=True)
                laps_data.to_csv('laps_data.csv')
                return laps_data
            except TypeError as e:
                return f"Error: {e}, session info is empty."
            except Exception as f:
                return f"Error: {f}"
    
        # def get_car_data(self):
        #     car_data = pd.DataFrame()
        #     for session in self.session_key:
        #         url = f"https://api.openf1.org/v1/car_data?session_key={session}"
        #         fetched = self._fetch_data(url)
        #         if not fetched.empty:
        #             car_data = car_data._append(fetched,ignore_index=True)
        #     return car_data

if __name__ == "__main__":
    retriever = DataRetriever(2023,2024,'2023-01-01','2024-03-01')

In [37]:
retriever.get_laps_data()

,meeting_key,session_key,driver_number,i1_speed,i2_speed,st_speed,date_start,lap_duration,is_pit_out_lap,duration_sector_1,duration_sector_2,duration_sector_3,segments_sector_1,segments_sector_2,segments_sector_3,lap_number
0,1229,9472,1,234.0,250.0,251.0,None,NaN,False,NaN,41.266,23.616,"[2064, 2048, 2049, 2049, 2051, 2051, 2049, 204...","[2051, 2051, 2051, 2049, 2049, 2049, 2049, 205...","[2048, 2048, 2048, 2049, 2048, 2048, 2049]",1
1,1229,9472,2,230.0,249.0,231.0,None,NaN,False,NaN,43.162,24.178,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2048, 2049, 2048, 0]",1
2,1229,9472,3,233.0,241.0,257.0,None,NaN,False,NaN,43.159,24.451,"[2064, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2048, 2049, 2049, 2049]",1
3,1229,9472,4,233.0,247.0,237.0,None,NaN,False,NaN,43.309,24.244,"[2064, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2051, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2049, 2049, 2049, 2049]",1
4,1229,9472,10,231.0,246.0,272.0,None,NaN,False,NaN,43.704,24.393,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2049, 2049, 2048, 2049, 2049, 2049]",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26448,1222,9213,23,210.0,182.0,306.0,2023-10-22T20:38:42.113000,102.791,False,27.417,41.044,34.330,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56
26449,1222,9213,27,211.0,183.0,302.0,2023-10-22T20:38:50.175000,102.927,False,27.534,41.125,34.268,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56
26450,1222,9213,44,NaN,186.0,302.0,2023-10-22T20:37:24.802000,100.743,False,26.818,40.181,33.744,"[None, 2048, 2048, 2048, 2048, 2049]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2064, 2064]",56
26451,1222,9213,55,218.0,186.0,309.0,2023-10-22T20:37:37.192000,101.178,False,27.191,40.433,33.554,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2064, 2064]",56
26452,1222,9213,77,205.0,183.0,298.0,2023-10-22T20:38:58.113000,103.696,False,27.811,41.537,34.348,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56

In [31]:
class OpenF1DataRetriever:
    
    def __init__(self):
        self.base_url = "https://api.openf1.org/v1"
        self.session_key = None
    
    def _fetch_data(self,url,iter):
        try:
            response = requests.get(url)
            response.raise_for_status()
            json_data = response.json()
            return json_data
        except requests.exceptions.HTTPError as e:
            return f"Error in the {iter}th iteration: {e}"
        except requests.exceptions.RequestException as f:
            return f"Error in the {iter}th iteration: {f}"

    
    def get_meeting_info(self, start_year: int, end_year: int):
        meeting_info = pd.DataFrame()
        for year in range(start_year,end_year+1):
            url = f"{self.base_url}/meetings?year={year}"
            fetched = self._fetch_data(url,year)
            meeting_info = meeting_info._append(fetched,ignore_index=True)
        meeting_info.to_csv('meeting_info.csv')
        return meeting_info

    
    def get_session_info(self, start_year: int, end_year: int):
        session_info = pd.DataFrame()
        for year in range(start_year,end_year+1):
            url = f"{self.base_url}/sessions?session_name=Race&year={year}"
            fetched = self._fetch_data(url,year)
            session_info = session_info._append(fetched,ignore_index=True)
        if self.session_key is None and not session_info.empty:
            self.session_key = list(set(session_info['session_key']))
        session_info.to_csv('session_info.csv')
        return session_info

    
    def get_weather_info(self):
        weather_info = pd.DataFrame()
        try:
            for session in self.session_key:
                url = f"{self.base_url}/weather?session_key={session}"
                fetched = self._fetch_data(url,session)
                weather_info = weather_info._append(fetched,ignore_index=True)
            weather_info.to_csv('weather_info.csv')
            return weather_info
        except TypeError as e:
            return f"Error: {e}, session info is empty."
        except Exception as f:
            return f"Error: {f}"

    
    def get_laps_data(self):
        laps_data = pd.DataFrame()
        try:
            for session in self.session_key:
                url = f"https://api.openf1.org/v1/laps?date_start>={start_date}"
                fetched = self._fetch_data(url,session)
                laps_data = laps_data._append(fetched,ignore_index=True)
            laps_data.to_csv('laps_data.csv')
            return laps_data
        except TypeError as e:
            return f"Error: {e}, session info is empty."
        except Exception as f:
            return f"Error: {f}"

    # def get_car_data(self):
    #     car_data = pd.DataFrame()
    #     for session in self.session_key:
    #         url = f"https://api.openf1.org/v1/car_data?session_key={session}"
    #         fetched = self._fetch_data(url)
    #         if not fetched.empty:
    #             car_data = car_data._append(fetched,ignore_index=True)
    #     return car_data

if __name__ == "__main__":
    retriever = OpenF1DataRetriever()

IndentationError: expected an indented block after 'for' statement on line 59 (4189712925.py, line 60)

In [26]:
retriever.get_session_info(2023,2024)

,location,country_key,country_code,country_name,circuit_key,circuit_short_name,session_type,session_name,date_start,date_end,gmt_offset,session_key,meeting_key,year
0,Sakhir,36,BRN,Bahrain,63,Sakhir,Race,Race,2023-03-05T15:00:00,2023-03-05T17:00:00,03:00:00,7953,1141,2023
1,Jeddah,153,KSA,Saudi Arabia,149,Jeddah,Race,Race,2023-03-19T17:00:00,2023-03-19T19:00:00,03:00:00,7779,1142,2023
2,Melbourne,5,AUS,Australia,10,Melbourne,Race,Race,2023-04-02T05:00:00,2023-04-02T07:00:00,10:00:00,7787,1143,2023
3,Baku,30,AZE,Azerbaijan,144,Baku,Race,Race,2023-04-30T11:00:00,2023-04-30T13:00:00,04:00:00,9070,1207,2023
4,Miami,19,USA,United States,151,Miami,Race,Race,2023-05-07T19:30:00,2023-05-07T21:30:00,-04:00:00,9078,1208,2023
5,Monaco,114,MON,Monaco,22,Monte Carlo,Race,Race,2023-05-28T13:00:00,2023-05-28T15:00:00,02:00:00,9094,1210,2023
6,Barcelona,1,ESP,Spain,15,Catalunya,Race,Race,2023-06-04T13:00:00,2023-06-04T15:00:00,02:00:00,9102,1211,2023
7,Montréal,46,CAN,Canada,23,Montreal,Race,Race,2023-06-18T18:00:00,2023-06-18T20:00:00,-04:00:00,9110,1212,2023
8,Spielberg,17,AUT,Austria,19,Spielberg,Race,Race,2023-07-02T13:00:00,2023-07-02T15:00:00,02:00:00,9118,1213,2023
9,Silverstone,2,GBR,Great Britain,2,Silverstone,Race,Race,2023-07-09T14:00:00,2023-07-09T16:00:00,01:00:00,9126,1214,2023
10,Budapest,14,HUN,Hungary,4,Hungaroring,Race,Race,2023-07-23T13:00:00,2023-07-23T15:00:00,02:00:00,9133,1215,2023
11,Spa-Francorchamps,16,BEL,Belgium,7,Spa-Francorchamps,Race,Race,2023-07-30T13:00:00,2023-07-30T15:00:00,02:00:00,9141,1216,2023
12,Zandvoort,133,NED,Netherlands,55,Zandvoort,Race,Race,2023-08-27T13:00:00,2023-08-27T15:00:00,02:00:00,9149,1217,2023
13,Monza,13,ITA,Italy,39,Monza,Race,Race,2023-09-03T13:00:00,2023-09-03T15:00:00,02:00:00,9157,1218,2023
14,Marina Bay,157,SGP,Singapore,61,Singapore,Race,Race,2023-09-17T12:00:00,2023-09-17T14:00:00,08:00:00,9165,1219,2023
15,Suzuka,4,JPN,Japan,46,Suzuka,Race,Race,2023-09-24T05:00:00,2023-09-24T07:00:00,09:00:00,9173,1220,2023
16,Lusail,149,QAT,Qatar,150,Lusail,Race,Race,2023-10-08T17:00:00,2023-10-08T19:00:00,03:00:00,9221,1221,2023
17,Austin,19,USA,United States,9,Austin,Race,Race,2023-10-22T19:00:00,2023-10-22T21:00:00,-05:00:00,9213,1222,2023
18,Mexico City,8,MEX,Mexico,65,Mexico City,Race,Race,2023-10-29T20:00:00,2023-10-29T22:00:00,-06:00:00,9181,1223,2023
19,São Paulo,10,BRA,Brazil,14,Interlagos,Race,Race,2023-11-05T17:00:00,2023-11-05T19:00:00,-03:00:00,9205,1224,2023
20,Las Vegas,19,USA,United States,152,Las Vegas,Race,Race,2023-11-19T06:00:00,2023-11-19T08:00:00,-08:00:00,9189,1225,2023
21,Yas Island,21,UAE,United Arab Emirates,70,Yas Marina Circuit,Race,Race,2023-11-26T13:00:00,2023-11-26T15:00:00,04:00:00,9197,1226,2023
22,Sakhir,36,BRN,Bahrain,63,Sakhir,Race,Race,2024-03-02T15:00:00,2024-03-02T17:00:00,03:00:00,9472,1229,2024
23,Jeddah,153,KSA,Saudi Arabia,149,Jeddah,Race,Race,2024-03-09T17:00:00,2024-03-09T19:00:00,03:00:00,9480,1230,2024

In [24]:
meeting_info.to_csv('meeting_info.csv')

In [30]:
start_date = '2023-01-01'
laps_data = pd.DataFrame()
url = f"https://api.openf1.org/v1/laps?date_start>={start_date}"
response = requests.get(url)
fetched = response.json()
laps_data = laps_data._append(fetched,ignore_index=True)
laps_data

,meeting_key,session_key,driver_number,i1_speed,i2_speed,st_speed,date_start,lap_duration,is_pit_out_lap,duration_sector_1,duration_sector_2,duration_sector_3,segments_sector_1,segments_sector_2,segments_sector_3,lap_number
0,1140,9222,63,222.0,231.0,185.0,2023-02-23T07:00:03.737000,NaN,True,NaN,47.609,25.153,[],[],[],1
1,1140,9222,24,190.0,219.0,149.0,2023-02-23T07:00:05.955000,NaN,True,NaN,51.359,29.109,[],[],[],1
2,1140,9222,23,225.0,214.0,84.0,2023-02-23T07:00:08.471000,NaN,True,NaN,54.064,30.610,[],[],[],1
3,1140,9222,55,209.0,127.0,189.0,2023-02-23T07:00:08.830000,NaN,True,NaN,46.139,29.943,[],[],[],1
4,1140,9222,22,201.0,220.0,46.0,2023-02-23T07:00:11.815000,NaN,True,NaN,49.704,31.868,[],[],[],1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67079,1230,9480,4,290.0,301.0,298.0,2024-03-09T18:23:55.567000,92.841,False,33.771,29.282,29.788,"[None, 2048, 2048, 2048, 2048, 2048, 2048, 204...","[2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",50
67080,1230,9480,44,291.0,314.0,320.0,2024-03-09T18:23:56.807000,93.314,False,34.397,29.264,29.653,"[None, 2048, 2048, 2048, 2048, 2048, 2048, 204...","[2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",50
67081,1230,9480,27,287.0,300.0,307.0,2024-03-09T18:24:26.750000,93.081,False,34.241,29.278,29.562,"[None, 2048, 2048, 2048, 2048, 2048, 2048, 204...","[2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",50
67082,1230,9480,20,288.0,301.0,305.0,2024-03-09T18:24:33.915000,94.603,False,35.144,29.638,29.821,"[None, 2048, 2048, 2048, 2048, 2048, 2048, 204...","[2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",50
67083,1230,9480,23,291.0,309.0,317.0,2024-03-09T18:24:38.827000,92.307,False,33.975,28.993,29.339,"[None, 2048, 2048, 2048, 2048, 2049, 2048, 204...","[2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",50

In [119]:
start_year = 2000
end_year = 2001
retriever.get_laps_data()

"Error: 'NoneType' object is not iterable, session info is empty."

In [99]:
retriever.get_laps_data()

,meeting_key,session_key,driver_number,i1_speed,i2_speed,st_speed,date_start,lap_duration,is_pit_out_lap,duration_sector_1,duration_sector_2,duration_sector_3,segments_sector_1,segments_sector_2,segments_sector_3,lap_number
0,1229,9472,1,234.0,250.0,251.0,None,NaN,False,NaN,41.266,23.616,"[2064, 2048, 2049, 2049, 2051, 2051, 2049, 204...","[2051, 2051, 2051, 2049, 2049, 2049, 2049, 205...","[2048, 2048, 2048, 2049, 2048, 2048, 2049]",1
1,1229,9472,2,230.0,249.0,231.0,None,NaN,False,NaN,43.162,24.178,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2048, 2049, 2048, 0]",1
2,1229,9472,3,233.0,241.0,257.0,None,NaN,False,NaN,43.159,24.451,"[2064, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2048, 2049, 2049, 2049]",1
3,1229,9472,4,233.0,247.0,237.0,None,NaN,False,NaN,43.309,24.244,"[2064, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2051, 2049, 2049, 2049, 204...","[2048, 2048, 2048, 2049, 2049, 2049, 2049]",1
4,1229,9472,10,231.0,246.0,272.0,None,NaN,False,NaN,43.704,24.393,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2048, 2049, 2049, 2048, 2049, 2049, 2049]",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26448,1222,9213,23,210.0,182.0,306.0,2023-10-22T20:38:42.113000,102.791,False,27.417,41.044,34.330,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56
26449,1222,9213,27,211.0,183.0,302.0,2023-10-22T20:38:50.175000,102.927,False,27.534,41.125,34.268,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56
26450,1222,9213,44,NaN,186.0,302.0,2023-10-22T20:37:24.802000,100.743,False,26.818,40.181,33.744,"[None, 2048, 2048, 2048, 2048, 2049]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2064, 2064]",56
26451,1222,9213,55,218.0,186.0,309.0,2023-10-22T20:37:37.192000,101.178,False,27.191,40.433,33.554,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2064, 2064]",56
26452,1222,9213,77,205.0,183.0,298.0,2023-10-22T20:38:58.113000,103.696,False,27.811,41.537,34.348,"[None, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2052, 0]",56

In [80]:
def fetch_url(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        json_data = response.json()
        return json_data
    except requests.exceptions.HTTPError as e:
        return f"Error: {e}"
    except requests.exceptions.RequestException as f:
        return f"Error: {f}"

In [81]:
test_urls = ['http://httpbin.org/user-agent',
             'http://httpbin.org/status/404',
             'http://httpbin.org/status/500',
             'httpx://invalid/url']

for i in test_urls:
    print(f"fetching {i}")
    print(fetch_url(i))

fetching http://httpbin.org/user-agent
{'user-agent': 'python-requests/2.31.0'}
fetching http://httpbin.org/status/404
Error: 404 Client Error: NOT FOUND for url: http://httpbin.org/status/404
fetching http://httpbin.org/status/500
Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://httpbin.org/status/500
fetching httpx://invalid/url
Error: No connection adapters were found for 'httpx://invalid/url'

In [67]:
url = 'http://httpbin.org/status/500'
response = requests.get(url)
try:    
    json_data = response.json()
    response.raise_for_status()
except requests.exceptions.HTTPError as e:
    print(f"Error: {e}")
except requests.exceptions.RequestException as f:
    print(f"Error: {f}")

Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://httpbin.org/status/500

In [31]:

url = 'http://httpbin.org/status/500'
response = requests.get(url)
# print(response.raise_for_status())
print(requests.exceptions.HTTPError)
#     print(f"Error: {e}")

# json_data = response.json()
# json_data
# return json_data

<class 'requests.exceptions.HTTPError'>

In [15]:
df = pd.DataFrame(json_data)
df

,driver_number,rpm,speed,n_gear,throttle,brake,drs,date,session_key,meeting_key
0,55,0,0,0,0,0,0,2023-09-15T12:45:02.318000,9159,1219
1,55,0,0,0,0,0,0,2023-09-15T12:45:02.598000,9159,1219
2,55,0,0,0,0,0,0,2023-09-15T12:45:02.918000,9159,1219
3,55,0,0,0,0,0,0,2023-09-15T12:45:03.279000,9159,1219
4,55,0,0,0,0,0,0,2023-09-15T12:45:03.519000,9159,1219
...,...,...,...,...,...,...,...,...,...,...
18444,55,0,0,0,104,104,8,2023-09-15T14:07:54.814000,9159,1219
18445,55,0,0,0,104,104,8,2023-09-15T14:07:55.054000,9159,1219
18446,55,0,0,0,104,104,8,2023-09-15T14:07:55.494000,9159,1219
18447,55,0,0,0,104,104,8,2023-09-15T14:07:55.894000,9159,1219
18448,55,0,0,0,104,104,8,2023-09-15T14:07:56.135000,9159,1219

In [223]:
meeting_info

,meeting_name,meeting_official_name,location,country_key,country_code,country_name,circuit_key,circuit_short_name,date_start,gmt_offset,meeting_key,year,meeting_code
0,Pre-Season Testing,FORMULA 1 ARAMCO PRE-SEASON TESTING 2023,Sakhir,36,BRN,Bahrain,63,Sakhir,2023-02-23T07:00:00,03:00:00,1140,2023,NaN
1,Bahrain Grand Prix,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023,Sakhir,36,BRN,Bahrain,63,Sakhir,2023-03-03T11:30:00,03:00:00,1141,2023,NaN
2,Saudi Arabian Grand Prix,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2023,Jeddah,153,KSA,Saudi Arabia,149,Jeddah,2023-03-17T13:30:00,03:00:00,1142,2023,NaN
3,Australian Grand Prix,FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2023,Melbourne,5,AUS,Australia,10,Melbourne,2023-03-31T01:30:00,11:00:00,1143,2023,NaN
4,Azerbaijan Grand Prix,FORMULA 1 AZERBAIJAN GRAND PRIX 2023,Baku,30,AZE,Azerbaijan,144,Baku,2023-04-28T09:30:00,04:00:00,1207,2023,NaN
5,Miami Grand Prix,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2023,Miami,19,USA,United States,151,Miami,2023-05-05T18:00:00,-04:00:00,1208,2023,NaN
6,Monaco Grand Prix,FORMULA 1 GRAND PRIX DE MONACO 2023,Monaco,114,MON,Monaco,22,Monte Carlo,2023-05-26T11:30:00,02:00:00,1210,2023,NaN
7,Spanish Grand Prix,FORMULA 1 AWS GRAN PREMIO DE ESPAÑA 2023,Barcelona,1,ESP,Spain,15,Catalunya,2023-06-02T11:30:00,02:00:00,1211,2023,NaN
8,Canadian Grand Prix,FORMULA 1 PIRELLI GRAND PRIX DU CANADA 2023,Montréal,46,CAN,Canada,23,Montreal,2023-06-16T17:30:00,-04:00:00,1212,2023,NaN
9,British Grand Prix,FORMULA 1 ARAMCO BRITISH GRAND PRIX 2023,Silverstone,2,GBR,Great Britain,2,Silverstone,2023-07-07T11:30:00,01:00:00,1214,2023,NaN
10,Hungarian Grand Prix,FORMULA 1 QATAR AIRWAYS HUNGARIAN GRAND PRIX 2023,Budapest,14,HUN,Hungary,4,Hungaroring,2023-07-21T11:30:00,02:00:00,1215,2023,NaN
11,Belgian Grand Prix,FORMULA 1 MSC CRUISES BELGIAN GRAND PRIX 2023,Spa-Francorchamps,16,BEL,Belgium,7,Spa-Francorchamps,2023-07-28T11:30:00,02:00:00,1216,2023,NaN
12,Dutch Grand Prix,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2023,Zandvoort,133,NED,Netherlands,55,Zandvoort,2023-08-25T10:30:00,02:00:00,1217,2023,NaN
13,Italian Grand Prix,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2023,Monza,13,ITA,Italy,39,Monza,2023-09-01T11:30:00,02:00:00,1218,2023,NaN
14,Singapore Grand Prix,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,Marina Bay,157,SGP,Singapore,61,Singapore,2023-09-15T09:30:00,08:00:00,1219,2023,NaN
15,Japanese Grand Prix,FORMULA 1 LENOVO JAPANESE GRAND PRIX 2023,Suzuka,4,JPN,Japan,46,Suzuka,2023-09-22T02:30:00,09:00:00,1220,2023,NaN
16,Qatar Grand Prix,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2023,Lusail,149,QAT,Qatar,150,Lusail,2023-10-06T13:30:00,03:00:00,1221,2023,NaN
17,United States Grand Prix,FORMULA 1 LENOVO UNITED STATES GRAND PRIX 2023,Austin,19,USA,United States,9,Austin,2023-10-20T17:30:00,-05:00:00,1222,2023,NaN
18,Mexico City Grand Prix,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2023,Mexico City,8,MEX,Mexico,65,Mexico City,2023-10-27T18:30:00,-06:00:00,1223,2023,NaN
19,São Paulo Grand Prix,FORMULA 1 ROLEX GRANDE PRÊMIO DE SÃO PAULO 2023,São Paulo,10,BRA,Brazil,14,Interlagos,2023-11-03T14:30:00,-03:00:00,1224,2023,NaN
20,Las Vegas Grand Prix,FORMULA 1 HEINEKEN SILVER LAS VEGAS GRAND PRIX...,Las Vegas,19,USA,United States,152,Las Vegas,2023-11-17T04:30:00,-08:00:00,1225,2023,NaN
21,Abu Dhabi Grand Prix,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,Yas Island,21,UAE,United Arab Emirates,70,Yas Marina Circuit,2023-11-24T09:30:00,04:00:00,1226,2023,NaN
0,Bahrain Grand Prix,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024,Sakhir,36,BRN,Bahrain,63,Sakhir,2024-02-29T11:30:00,03:00:00,1229,2024,BRN
1,Saudi Arabian Grand Prix,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2024,Jeddah,153,KSA,Saudi Arabia,149,Jeddah,2024-03-07T13:30:00,03:00:00,1230,2024,KSA

In [108]:
json_data['MRData']['RaceTable']['Races'][0]['Results']

[{'number': '11',
  'position': '1',
  'positionText': '1',
  'points': '25',
  'Driver': {'driverId': 'perez',
   'permanentNumber': '11',
   'code': 'PER',
   'url': 'http://en.wikipedia.org/wiki/Sergio_P%C3%A9rez',
   'givenName': 'Sergio',
   'familyName': 'Pérez',
   'dateOfBirth': '1990-01-26',
   'nationality': 'Mexican'},
  'Constructor': {'constructorId': 'red_bull',
   'url': 'http://en.wikipedia.org/wiki/Red_Bull_Racing',
   'name': 'Red Bull',
   'nationality': 'Austrian'},
  'grid': '1',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4874894', 'time': '1:21:14.894'},
  'FastestLap': {'rank': '2',
   'lap': '38',
   'Time': {'time': '1:32.188'},
   'AverageSpeed': {'units': 'kph', 'speed': '241.098'}}},
 {'number': '1',
  'position': '2',
  'positionText': '2',
  'points': '19',
  'Driver': {'driverId': 'max_verstappen',
   'permanentNumber': '33',
   'code': 'VER',
   'url': 'http://en.wikipedia.org/wiki/Max_Verstappen',
   'givenName': 'Max',
   'familyName': 'Verstappen',
   'dateOfBirth': '1997-09-30',
   'nationality': 'Dutch'},
  'Constructor': {'constructorId': 'red_bull',
   'url': 'http://en.wikipedia.org/wiki/Red_Bull_Racing',
   'name': 'Red Bull',
   'nationality': 'Austrian'},
  'grid': '15',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4880249', 'time': '+5.355'},
  'FastestLap': {'rank': '1',
   'lap': '50',
   'Time': {'time': '1:31.906'},
   'AverageSpeed': {'units': 'kph', 'speed': '241.838'}}},
 {'number': '14',
  'position': '3',
  'positionText': '3',
  'points': '15',
  'Driver': {'driverId': 'alonso',
   'permanentNumber': '14',
   'code': 'ALO',
   'url': 'http://en.wikipedia.org/wiki/Fernando_Alonso',
   'givenName': 'Fernando',
   'familyName': 'Alonso',
   'dateOfBirth': '1981-07-29',
   'nationality': 'Spanish'},
  'Constructor': {'constructorId': 'aston_martin',
   'url': 'http://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One',
   'name': 'Aston Martin',
   'nationality': 'British'},
  'grid': '2',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4895622', 'time': '+20.728'},
  'FastestLap': {'rank': '3',
   'lap': '50',
   'Time': {'time': '1:32.240'},
   'AverageSpeed': {'units': 'kph', 'speed': '240.962'}}},
 {'number': '63',
  'position': '4',
  'positionText': '4',
  'points': '12',
  'Driver': {'driverId': 'russell',
   'permanentNumber': '63',
   'code': 'RUS',
   'url': 'http://en.wikipedia.org/wiki/George_Russell_(racing_driver)',
   'givenName': 'George',
   'familyName': 'Russell',
   'dateOfBirth': '1998-02-15',
   'nationality': 'British'},
  'Constructor': {'constructorId': 'mercedes',
   'url': 'http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One',
   'name': 'Mercedes',
   'nationality': 'German'},
  'grid': '3',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4900760', 'time': '+25.866'},
  'FastestLap': {'rank': '4',
   'lap': '50',
   'Time': {'time': '1:32.433'},
   'AverageSpeed': {'units': 'kph', 'speed': '240.459'}}},
 {'number': '44',
  'position': '5',
  'positionText': '5',
  'points': '10',
  'Driver': {'driverId': 'hamilton',
   'permanentNumber': '44',
   'code': 'HAM',
   'url': 'http://en.wikipedia.org/wiki/Lewis_Hamilton',
   'givenName': 'Lewis',
   'familyName': 'Hamilton',
   'dateOfBirth': '1985-01-07',
   'nationality': 'British'},
  'Constructor': {'constructorId': 'mercedes',
   'url': 'http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One',
   'name': 'Mercedes',
   'nationality': 'German'},
  'grid': '7',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4905959', 'time': '+31.065'},
  'FastestLap': {'rank': '6',
   'lap': '47',
   'Time': {'time': '1:32.941'},
   'AverageSpeed': {'units': 'kph', 'speed': '239.145'}}},
 {'number': '55',
  'position': '6',
  'positionText': '6',
  'points': '8',
  'Driver': {'driverId': 'sainz',
   'permanentNumber': '55',
   'code': 'SAI',
   'url': 'http://en.wikipedia.org/wiki/Carlos_Sainz_Jr.',
   'givenName': 'Carlos',
   'familyName': 'Sainz',
   'dateOfBirth': '1994-09-01',
   'nationality': 'Spanish'},
  'Constructor': {'constructorId': 'ferrari',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
   'name': 'Ferrari',
   'nationality': 'Italian'},
  'grid': '4',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4910770', 'time': '+35.876'},
  'FastestLap': {'rank': '5',
   'lap': '50',
   'Time': {'time': '1:32.822'},
   'AverageSpeed': {'units': 'kph', 'speed': '239.451'}}},
 {'number': '16',
  'position': '7',
  'positionText': '7',
  'points': '6',
  'Driver': {'driverId': 'leclerc',
   'permanentNumber': '16',
   'code': 'LEC',
   'url': 'http://en.wikipedia.org/wiki/Charles_Leclerc',
   'givenName': 'Charles',
   'familyName': 'Leclerc',
   'dateOfBirth': '1997-10-16',
   'nationality': 'Monegasque'},
  'Constructor': {'constructorId': 'ferrari',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
   'name': 'Ferrari',
   'nationality': 'Italian'},
  'grid': '12',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4918056', 'time': '+43.162'},
  'FastestLap': {'rank': '7',
   'lap': '47',
   'Time': {'time': '1:33.056'},
   'AverageSpeed': {'units': 'kph', 'speed': '238.849'}}},
 {'number': '31',
  'position': '8',
  'positionText': '8',
  'points': '4',
  'Driver': {'driverId': 'ocon',
   'permanentNumber': '31',
   'code': 'OCO',
   'url': 'http://en.wikipedia.org/wiki/Esteban_Ocon',
   'givenName': 'Esteban',
   'familyName': 'Ocon',
   'dateOfBirth': '1996-09-17',
   'nationality': 'French'},
  'Constructor': {'constructorId': 'alpine',
   'url': 'http://en.wikipedia.org/wiki/Alpine_F1_Team',
   'name': 'Alpine F1 Team',
   'nationality': 'French'},
  'grid': '6',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4927726', 'time': '+52.832'},
  'FastestLap': {'rank': '8',
   'lap': '49',
   'Time': {'time': '1:33.222'},
   'AverageSpeed': {'units': 'kph', 'speed': '238.424'}}},
 {'number': '10',
  'position': '9',
  'positionText': '9',
  'points': '2',
  'Driver': {'driverId': 'gasly',
   'permanentNumber': '10',
   'code': 'GAS',
   'url': 'http://en.wikipedia.org/wiki/Pierre_Gasly',
   'givenName': 'Pierre',
   'familyName': 'Gasly',
   'dateOfBirth': '1996-02-07',
   'nationality': 'French'},
  'Constructor': {'constructorId': 'alpine',
   'url': 'http://en.wikipedia.org/wiki/Alpine_F1_Team',
   'name': 'Alpine F1 Team',
   'nationality': 'French'},
  'grid': '9',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4929641', 'time': '+54.747'},
  'FastestLap': {'rank': '10',
   'lap': '50',
   'Time': {'time': '1:33.392'},
   'AverageSpeed': {'units': 'kph', 'speed': '237.990'}}},
 {'number': '20',
  'position': '10',
  'positionText': '10',
  'points': '1',
  'Driver': {'driverId': 'kevin_magnussen',
   'permanentNumber': '20',
   'code': 'MAG',
   'url': 'http://en.wikipedia.org/wiki/Kevin_Magnussen',
   'givenName': 'Kevin',
   'familyName': 'Magnussen',
   'dateOfBirth': '1992-10-05',
   'nationality': 'Danish'},
  'Constructor': {'constructorId': 'haas',
   'url': 'http://en.wikipedia.org/wiki/Haas_F1_Team',
   'name': 'Haas F1 Team',
   'nationality': 'American'},
  'grid': '13',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4939720', 'time': '+1:04.826'},
  'FastestLap': {'rank': '9',
   'lap': '44',
   'Time': {'time': '1:33.374'},
   'AverageSpeed': {'units': 'kph', 'speed': '238.036'}}},
 {'number': '22',
  'position': '11',
  'positionText': '11',
  'points': '0',
  'Driver': {'driverId': 'tsunoda',
   'permanentNumber': '22',
   'code': 'TSU',
   'url': 'http://en.wikipedia.org/wiki/Yuki_Tsunoda',
   'givenName': 'Yuki',
   'familyName': 'Tsunoda',
   'dateOfBirth': '2000-05-11',
   'nationality': 'Japanese'},
  'Constructor': {'constructorId': 'alphatauri',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_AlphaTauri',
   'name': 'AlphaTauri',
   'nationality': 'Italian'},
  'grid': '16',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4942388', 'time': '+1:07.494'},
  'FastestLap': {'rank': '14',
   'lap': '50',
   'Time': {'time': '1:33.931'},
   'AverageSpeed': {'units': 'kph', 'speed': '236.624'}}},
 {'number': '27',
  'position': '12',
  'positionText': '12',
  'points': '0',
  'Driver': {'driverId': 'hulkenberg',
   'permanentNumber': '27',
   'code': 'HUL',
   'url': 'http://en.wikipedia.org/wiki/Nico_H%C3%BClkenberg',
   'givenName': 'Nico',
   'familyName': 'Hülkenberg',
   'dateOfBirth': '1987-08-19',
   'nationality': 'German'},
  'Constructor': {'constructorId': 'haas',
   'url': 'http://en.wikipedia.org/wiki/Haas_F1_Team',
   'name': 'Haas F1 Team',
   'nationality': 'American'},
  'grid': '10',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4945482', 'time': '+1:10.588'},
  'FastestLap': {'rank': '12',
   'lap': '50',
   'Time': {'time': '1:33.780'},
   'AverageSpeed': {'units': 'kph', 'speed': '237.005'}}},
 {'number': '24',
  'position': '13',
  'positionText': '13',
  'points': '0',
  'Driver': {'driverId': 'zhou',
   'permanentNumber': '24',
   'code': 'ZHO',
   'url': 'http://en.wikipedia.org/wiki/Zhou_Guanyu',
   'givenName': 'Guanyu',
   'familyName': 'Zhou',
   'dateOfBirth': '1999-05-30',
   'nationality': 'Chinese'},
  'Constructor': {'constructorId': 'alfa',
   'url': 'http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One',
   'name': 'Alfa Romeo',
   'nationality': 'Swiss'},
  'grid': '11',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4950954', 'time': '+1:16.060'},
  'FastestLap': {'rank': '13',
   'lap': '49',
   'Time': {'time': '1:33.894'},
   'AverageSpeed': {'units': 'kph', 'speed': '236.718'}}},
 {'number': '21',
  'position': '14',
  'positionText': '14',
  'points': '0',
  'Driver': {'driverId': 'de_vries',
   'permanentNumber': '21',
   'code': 'DEV',
   'url': 'http://en.wikipedia.org/wiki/Nyck_de_Vries',
   'givenName': 'Nyck',
   'familyName': 'de Vries',
   'dateOfBirth': '1995-02-06',
   'nationality': 'Dutch'},
  'Constructor': {'constructorId': 'alphatauri',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_AlphaTauri',
   'name': 'AlphaTauri',
   'nationality': 'Italian'},
  'grid': '18',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4952372', 'time': '+1:17.478'},
  'FastestLap': {'rank': '11',
   'lap': '49',
   'Time': {'time': '1:33.609'},
   'AverageSpeed': {'units': 'kph', 'speed': '237.438'}}},
 {'number': '81',
  'position': '15',
  'positionText': '15',
  'points': '0',
  'Driver': {'driverId': 'piastri',
   'permanentNumber': '81',
   'code': 'PIA',
   'url': 'http://en.wikipedia.org/wiki/Oscar_Piastri',
   'givenName': 'Oscar',
   'familyName': 'Piastri',
   'dateOfBirth': '2001-04-06',
   'nationality': 'Australian'},
  'Constructor': {'constructorId': 'mclaren',
   'url': 'http://en.wikipedia.org/wiki/McLaren',
   'name': 'McLaren',
   'nationality': 'British'},
  'grid': '8',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4959915', 'time': '+1:25.021'},
  'FastestLap': {'rank': '16',
   'lap': '48',
   'Time': {'time': '1:34.287'},
   'AverageSpeed': {'units': 'kph', 'speed': '235.731'}}},
 {'number': '2',
  'position': '16',
  'positionText': '16',
  'points': '0',
  'Driver': {'driverId': 'sargeant',
   'permanentNumber': '2',
   'code': 'SAR',
   'url': 'http://en.wikipedia.org/wiki/Logan_Sargeant',
   'givenName': 'Logan',
   'familyName': 'Sargeant',
   'dateOfBirth': '2000-12-31',
   'nationality': 'American'},
  'Constructor': {'constructorId': 'williams',
   'url': 'http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering',
   'name': 'Williams',
   'nationality': 'British'},
  'grid': '20',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4961187', 'time': '+1:26.293'},
  'FastestLap': {'rank': '18',
   'lap': '49',
   'Time': {'time': '1:34.469'},
   'AverageSpeed': {'units': 'kph', 'speed': '235.277'}}},
 {'number': '4',
  'position': '17',
  'positionText': '17',
  'points': '0',
  'Driver': {'driverId': 'norris',
   'permanentNumber': '4',
   'code': 'NOR',
   'url': 'http://en.wikipedia.org/wiki/Lando_Norris',
   'givenName': 'Lando',
   'familyName': 'Norris',
   'dateOfBirth': '1999-11-13',
   'nationality': 'British'},
  'Constructor': {'constructorId': 'mclaren',
   'url': 'http://en.wikipedia.org/wiki/McLaren',
   'name': 'McLaren',
   'nationality': 'British'},
  'grid': '19',
  'laps': '50',
  'status': 'Finished',
  'Time': {'millis': '4961339', 'time': '+1:26.445'},
  'FastestLap': {'rank': '15',
   'lap': '49',
   'Time': {'time': '1:34.122'},
   'AverageSpeed': {'units': 'kph', 'speed': '236.144'}}},
 {'number': '77',
  'position': '18',
  'positionText': '18',
  'points': '0',
  'Driver': {'driverId': 'bottas',
   'permanentNumber': '77',
   'code': 'BOT',
   'url': 'http://en.wikipedia.org/wiki/Valtteri_Bottas',
   'givenName': 'Valtteri',
   'familyName': 'Bottas',
   'dateOfBirth': '1989-08-28',
   'nationality': 'Finnish'},
  'Constructor': {'constructorId': 'alfa',
   'url': 'http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One',
   'name': 'Alfa Romeo',
   'nationality': 'Swiss'},
  'grid': '14',
  'laps': '49',
  'status': '+1 Lap',
  'FastestLap': {'rank': '17',
   'lap': '37',
   'Time': {'time': '1:34.384'},
   'AverageSpeed': {'units': 'kph', 'speed': '235.489'}}},
 {'number': '23',
  'position': '19',
  'positionText': 'R',
  'points': '0',
  'Driver': {'driverId': 'albon',
   'permanentNumber': '23',
   'code': 'ALB',
   'url': 'http://en.wikipedia.org/wiki/Alexander_Albon',
   'givenName': 'Alexander',
   'familyName': 'Albon',
   'dateOfBirth': '1996-03-23',
   'nationality': 'Thai'},
  'Constructor': {'constructorId': 'williams',
   'url': 'http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering',
   'name': 'Williams',
   'nationality': 'British'},
  'grid': '17',
  'laps': '27',
  'status': 'Brakes',
  'FastestLap': {'rank': '20',
   'lap': '24',
   'Time': {'time': '1:35.567'},
   'AverageSpeed': {'units': 'kph', 'speed': '232.574'}}},
 {'number': '18',
  'position': '20',
  'positionText': 'R',
  'points': '0',
  'Driver': {'driverId': 'stroll',
   'permanentNumber': '18',
   'code': 'STR',
   'url': 'http://en.wikipedia.org/wiki/Lance_Stroll',
   'givenName': 'Lance',
   'familyName': 'Stroll',
   'dateOfBirth': '1998-10-29',
   'nationality': 'Canadian'},
  'Constructor': {'constructorId': 'aston_martin',
   'url': 'http://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One',
   'name': 'Aston Martin',
   'nationality': 'British'},
  'grid': '5',
  'laps': '16',
  'status': 'Engine',
  'FastestLap': {'rank': '19',
   'lap': '7',
   'Time': {'time': '1:35.140'},
   'AverageSpeed': {'units': 'kph', 'speed': '233.617'}}}]

In [ ]:
try:
    conn = psycopg2.connect("host=127.0.0.1 dbname=postgres password=root")
except psycopg2.

In [3]:
import boto3
import pathlib

# script_path = pathlib.Path(__file__).parent.resolve()
# print(script_path)

In [4]:
p = pathlib.Path(__file__)
print(p)

NameError: name '__file__' is not defined

In [3]:
import pathlib

In [4]:
from pathlib import Path
import os

In [7]:
p = Path('.')

In [8]:
print(p)

.

In [5]:
p = pathlib.Path(__file__)

NameError: name '__file__' is not defined

In [10]:
help(Path)

Help on class Path in module pathlib:

class Path(PurePath)
 |  Path(*args, **kwargs)
 |
 |  PurePath subclass that can make system calls.
 |
 |  Path represents a filesystem path but unlike PurePath, also offers
 |  methods to do system calls on path objects. Depending on your system,
 |  instantiating a Path will return either a PosixPath or a WindowsPath
 |  object. You can also instantiate a PosixPath or WindowsPath directly,
 |  but cannot instantiate a WindowsPath on a POSIX system or vice versa.
 |
 |  Method resolution order:
 |      Path
 |      PurePath
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __enter__(self)
 |
 |  __exit__(self, t, v, tb)
 |
 |  __init__(self, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  absolute(self)
 |      Return an absolute version of this path by prepending the current
 |      working directory. No normalization or symlink resolution is performed.
 |
 |      Use resolve() to get the canonical path to a file.
 |
 |  chmod(self, mode, *, follow_symlinks=True)
 |      Change the permissions of the path, like os.chmod().
 |
 |  exists(self, *, follow_symlinks=True)
 |      Whether this path exists.
 |
 |      This method normally follows symlinks; to check whether a symlink exists,
 |      add the argument follow_symlinks=False.
 |
 |  expanduser(self)
 |      Return a new path with expanded ~ and ~user constructs
 |      (as returned by os.path.expanduser)
 |
 |  glob(self, pattern, *, case_sensitive=None)
 |      Iterate over this subtree and yield all existing files (of any
 |      kind, including directories) matching the given relative pattern.
 |
 |  group(self)
 |      Return the group name of the file gid.
 |
 |  hardlink_to(self, target)
 |      Make this path a hard link pointing to the same file as *target*.
 |
 |      Note the order of arguments (self, target) is the reverse of os.link's.
 |
 |  is_block_device(self)
 |      Whether this path is a block device.
 |
 |  is_char_device(self)
 |      Whether this path is a character device.
 |
 |  is_dir(self)
 |      Whether this path is a directory.
 |
 |  is_fifo(self)
 |      Whether this path is a FIFO.
 |
 |  is_file(self)
 |      Whether this path is a regular file (also True for symlinks pointing
 |      to regular files).
 |
 |  is_junction(self)
 |      Whether this path is a junction.
 |
 |  is_mount(self)
 |      Check if this path is a mount point
 |
 |  is_socket(self)
 |      Whether this path is a socket.
 |
 |  is_symlink(self)
 |      Whether this path is a symbolic link.
 |
 |  iterdir(self)
 |      Yield path objects of the directory contents.
 |
 |      The children are yielded in arbitrary order, and the
 |      special entries '.' and '..' are not included.
 |
 |  lchmod(self, mode)
 |      Like chmod(), except if the path points to a symlink, the symlink's
 |      permissions are changed, rather than its target's.
 |
 |  lstat(self)
 |      Like stat(), except if the path points to a symlink, the symlink's
 |      status information is returned, rather than its target's.
 |
 |  mkdir(self, mode=511, parents=False, exist_ok=False)
 |      Create a new directory at this given path.
 |
 |  open(self, mode='r', buffering=-1, encoding=None, errors=None, newline=None)
 |      Open the file pointed by this path and return a file object, as
 |      the built-in open() function does.
 |
 |  owner(self)
 |      Return the login name of the file owner.
 |
 |  read_bytes(self)
 |      Open the file in bytes mode, read it, and close the file.
 |
 |  read_text(self, encoding=None, errors=None)
 |      Open the file in text mode, read it, and close the file.
 |
 |  readlink(self)
 |      Return the path to which the symbolic link points.
 |
 |  rename(self, target)
 |      Rename this path to the target path.
 |
 |      The target path may be absolute or relative. Relative paths are
 |      interpreted relative to the current working directory, *not* the
 |      directory of the Path object.
 |
 |      Returns the new Path instance pointing to the target path.
 |
 |  replace(self, target)
 |      Rename this path to the target path, overwriting if that path exists.
 |
 |      The target path may be absolute or relative. Relative paths are
 |      interpreted relative to the current working directory, *not* the
 |      directory of the Path object.
 |
 |      Returns the new Path instance pointing to the target path.
 |
 |  resolve(self, strict=False)
 |      Make the path absolute, resolving all symlinks on the way and also
 |      normalizing it.
 |
 |  rglob(self, pattern, *, case_sensitive=None)
 |      Recursively yield all existing files (of any kind, including
 |      directories) matching the given relative pattern, anywhere in
 |      this subtree.
 |
 |  rmdir(self)
 |      Remove this directory.  The directory must be empty.
 |
 |  samefile(self, other_path)
 |      Return whether other_path is the same or not as this file
 |      (as returned by os.path.samefile()).
 |
 |  stat(self, *, follow_symlinks=True)
 |      Return the result of the stat() system call on this path, like
 |      os.stat() does.
 |
 |  symlink_to(self, target, target_is_directory=False)
 |      Make this path a symlink pointing to the target path.
 |      Note the order of arguments (link, target) is the reverse of os.symlink.
 |
 |  touch(self, mode=438, exist_ok=True)
 |      Create this file with the given access mode, if it doesn't exist.
 |
 |  unlink(self, missing_ok=False)
 |      Remove this file or link.
 |      If the path is a directory, use rmdir() instead.
 |
 |  walk(self, top_down=True, on_error=None, follow_symlinks=False)
 |      Walk the directory tree from this directory, similar to os.walk().
 |
 |  write_bytes(self, data)
 |      Open the file in bytes mode, write to it, and close the file.
 |
 |  write_text(self, data, encoding=None, errors=None, newline=None)
 |      Open the file in text mode, write to it, and close the file.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  cwd() from builtins.type
 |      Return a new path pointing to the current working directory.
 |
 |  home() from builtins.type
 |      Return a new path pointing to the user's home directory (as
 |      returned by os.path.expanduser('~')).
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(cls, *args, **kwargs)
 |      Construct a PurePath from one or several strings and or existing
 |      PurePath objects.  The strings and path objects are combined so as
 |      to yield a canonicalized path, which is incorporated into the
 |      new PurePath object.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from PurePath:
 |
 |  __bytes__(self)
 |      Return the bytes representation of the path.  This is only
 |      recommended to use under Unix.
 |
 |  __eq__(self, other)
 |      Return self==value.
 |
 |  __fspath__(self)
 |
 |  __ge__(self, other)
 |      Return self>=value.
 |
 |  __gt__(self, other)
 |      Return self>value.
 |
 |  __hash__(self)
 |      Return hash(self).
 |
 |  __le__(self, other)
 |      Return self<=value.
 |
 |  __lt__(self, other)
 |      Return self<value.
 |
 |  __reduce__(self)
 |      Helper for pickle.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  __rtruediv__(self, key)
 |
 |  __str__(self)
 |      Return the string representation of the path, suitable for
 |      passing to system calls.
 |
 |  __truediv__(self, key)
 |
 |  as_posix(self)
 |      Return the string representation of the path with forward (/)
 |      slashes.
 |
 |  as_uri(self)
 |      Return the path as a 'file' URI.
 |
 |  is_absolute(self)
 |      True if the path is absolute (has both a root and, if applicable,
 |      a drive).
 |
 |  is_relative_to(self, other, /, *_deprecated)
 |      Return True if the path is relative to another path or False.
 |
 |  is_reserved(self)
 |      Return True if the path contains one of the special names reserved
 |      by the system, if any.
 |
 |  joinpath(self, *pathsegments)
 |      Combine this path with one or several arguments, and return a
 |      new path representing either a subpath (if all arguments are relative
 |      paths) or a totally different path (if one of the arguments is
 |      anchored).
 |
 |  match(self, path_pattern, *, case_sensitive=None)
 |      Return True if this path matches the given pattern.
 |
 |  relative_to(self, other, /, *_deprecated, walk_up=False)
 |      Return the relative path to another path identified by the passed
 |      arguments.  If the operation is not possible (because this is not
 |      related to the other path), raise ValueError.
 |
 |      The *walk_up* parameter controls whether `..` may be used to resolve
 |      the path.
 |
 |  with_name(self, name)
 |      Return a new path with the file name changed.
 |
 |  with_segments(self, *pathsegments)
 |      Construct a new path object from any number of path-like objects.
 |      Subclasses may override this method to customize how new path objects
 |      are created from methods like `iterdir()`.
 |
 |  with_stem(self, stem)
 |      Return a new path with the stem changed.
 |
 |  with_suffix(self, suffix)
 |      Return a new path with the file suffix changed.  If the path
 |      has no suffix, add given suffix.  If the given suffix is an empty
 |      string, remove the suffix from the path.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from PurePath:
 |
 |  anchor
 |      The concatenation of the drive and root, or ''.
 |
 |  drive
 |      The drive prefix (letter or UNC path), if any.
 |
 |  name
 |      The final path component, if any.
 |
 |  parent
 |      The logical parent of the path.
 |
 |  parents
 |      A sequence of this path's logical parents.
 |
 |  parts
 |      An object providing sequence-like access to the
 |      components in the filesystem path.
 |
 |  root
 |      The root of the path, if any.
 |
 |  stem
 |      The final path component, minus its last suffix.
 |
 |  suffix
 |      The final component's last suffix, if any.
 |
 |      This includes the leading period. For example: '.txt'
 |
 |  suffixes
 |      A list of the final component's suffixes, if any.
 |
 |      These include the leading periods. For example: ['.tar', '.gz']

'C:\\Users\\Windows10\\Documents\\formula1_project'

In [6]:
script_path = pathlib.os.path.abspath('').parent.resolve()

AttributeError: 'str' object has no attribute 'parent'

In [1]:
!python --version

Python 3.12.0